/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codeptit.QuanLyCuaHangLapTop.View;

import codeptit.QuanLyCuaHangLapTop.Model.ChiTietHoaDon;
import codeptit.QuanLyCuaHangLapTop.Model.HoaDon;
import codeptit.QuanLyCuaHangLapTop.Model.NhaCungCap;
import codeptit.QuanLyCuaHangLapTop.Model.SanPham;
import codeptit.QuanLyCuaHangLapTop.Model.TaiKhoan;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class DoanhThu_View extends javax.swing.JFrame {
    private ArrayList<HoaDon> list;
    /**
     * Creates new form DoanhThu_View
     */
    public DoanhThu_View() {
        list = HoaDon.hoaDonList();
        initComponents();
        jTextField_TongTien.setEditable(false);
        showJComboBox();
        showDoanhThu(list);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Thang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_MaNV = new javax.swing.JTextField();
        jTextField_Nam = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_MaKH = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_DoanhThu = new javax.swing.JTable();
        jButton_TimKiem = new javax.swing.JButton();
        jButton_LamMoi = new javax.swing.JButton();
        jButton_Exit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField_TongTien = new javax.swing.JTextField();
        jComboBox_NCC = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Doanh Thu");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 204));
        jLabel2.setText("Tháng:");

        jTextField_Thang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 204));
        jLabel3.setText("Năm:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 204));
        jLabel4.setText("Mã nhân viên:");

        jTextField_MaNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField_Nam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 204));
        jLabel5.setText("Nhà cung cấp:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 204));
        jLabel6.setText("Mã khách hàng:");

        jTextField_MaKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTable_DoanhThu = new JTable() {
            public boolean isCellEditable(int row, int column) {
                for(int i = 0; i < jTable_DoanhThu.getRowCount(); i++) {
                    if(row == i) return false;
                }
                return true;
            }
        };
        jTable_DoanhThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã hóa đơn", "Mã nhân viên", "Mã khách hàng", "Mã sản phẩm", "Số lượng", "Ngày bán", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_DoanhThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_DoanhThuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_DoanhThu);
        if (jTable_DoanhThu.getColumnModel().getColumnCount() > 0) {
            jTable_DoanhThu.getColumnModel().getColumn(0).setMinWidth(40);
            jTable_DoanhThu.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTable_DoanhThu.getColumnModel().getColumn(0).setMaxWidth(60);
            jTable_DoanhThu.getColumnModel().getColumn(1).setMinWidth(80);
            jTable_DoanhThu.getColumnModel().getColumn(1).setPreferredWidth(0);
            jTable_DoanhThu.getColumnModel().getColumn(1).setMaxWidth(120);
            jTable_DoanhThu.getColumnModel().getColumn(2).setMinWidth(90);
            jTable_DoanhThu.getColumnModel().getColumn(2).setPreferredWidth(0);
            jTable_DoanhThu.getColumnModel().getColumn(2).setMaxWidth(100);
            jTable_DoanhThu.getColumnModel().getColumn(3).setMinWidth(100);
            jTable_DoanhThu.getColumnModel().getColumn(3).setPreferredWidth(0);
            jTable_DoanhThu.getColumnModel().getColumn(3).setMaxWidth(120);
            jTable_DoanhThu.getColumnModel().getColumn(4).setMinWidth(90);
            jTable_DoanhThu.getColumnModel().getColumn(4).setPreferredWidth(0);
            jTable_DoanhThu.getColumnModel().getColumn(4).setMaxWidth(100);
            jTable_DoanhThu.getColumnModel().getColumn(5).setMinWidth(65);
            jTable_DoanhThu.getColumnModel().getColumn(5).setPreferredWidth(0);
            jTable_DoanhThu.getColumnModel().getColumn(5).setMaxWidth(80);
            jTable_DoanhThu.getColumnModel().getColumn(6).setMinWidth(70);
            jTable_DoanhThu.getColumnModel().getColumn(6).setPreferredWidth(0);
            jTable_DoanhThu.getColumnModel().getColumn(6).setMaxWidth(80);
            jTable_DoanhThu.getColumnModel().getColumn(7).setMinWidth(80);
            jTable_DoanhThu.getColumnModel().getColumn(7).setPreferredWidth(0);
            jTable_DoanhThu.getColumnModel().getColumn(7).setMaxWidth(100);
        }

        jButton_TimKiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_TimKiem.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\Zoom-icon.png")); // NOI18N
        jButton_TimKiem.setText("Tìm Kiếm");
        jButton_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TimKiemActionPerformed(evt);
            }
        });

        jButton_LamMoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_LamMoi.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\Reload-icon.png")); // NOI18N
        jButton_LamMoi.setText("Làm Mới");
        jButton_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LamMoiActionPerformed(evt);
            }
        });

        jButton_Exit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Exit.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\Button-Close-icon.png")); // NOI18N
        jButton_Exit.setText("Thoát");
        jButton_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExitActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Tổng tiền:");

        jTextField_TongTien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jComboBox_NCC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_Thang, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_Nam, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_MaKH)
                    .addComponent(jComboBox_NCC, 0, 140, Short.MAX_VALUE))
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jButton_TimKiem)
                .addGap(105, 105, 105)
                .addComponent(jButton_LamMoi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(jButton_Exit)
                .addGap(61, 61, 61))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel1))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(188, 188, 188))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_Thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_Nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox_NCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_MaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_TimKiem)
                    .addComponent(jButton_LamMoi)
                    .addComponent(jButton_Exit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 54;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_DoanhThuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_DoanhThuMouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable_DoanhThu.getSelectedRow();
        DefaultTableModel dtm = (DefaultTableModel) jTable_DoanhThu.getModel();
        jTextField_MaNV.setText(dtm.getValueAt(selectedRow, 2).toString());
        jTextField_MaKH.setText(dtm.getValueAt(selectedRow, 3).toString());
        // Nha cung cap
        List<String> data = NhaCungCap.tenNCC();
        for (int i = 0; i < data.size(); i++) {
            if (data.get(i).contains(SanPham.getNCC(dtm.getValueAt(selectedRow, 4).toString()))) {
                jComboBox_NCC.setSelectedItem(data.get(i));
            }
        }
        // Thang va nam
        String[] temp = dtm.getValueAt(selectedRow, 6).toString().split("/");
        jTextField_Thang.setText(temp[1]);
        jTextField_Nam.setText(temp[2]);
    }//GEN-LAST:event_jTable_DoanhThuMouseClicked

    private void jButton_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton_ExitActionPerformed

    private void jButton_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LamMoiActionPerformed
        // TODO add your handling code here:
        // Xoa table
        DefaultTableModel dtm = (DefaultTableModel) jTable_DoanhThu.getModel();
        while(jTable_DoanhThu.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        
        jTextField_Thang.setText("");
        jTextField_Nam.setText("");
        jTextField_MaNV.setText("");
        jTextField_MaKH.setText("");
        jComboBox_NCC.setSelectedIndex(0);
        
        showDoanhThu(list);
    }//GEN-LAST:event_jButton_LamMoiActionPerformed

    private void jButton_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TimKiemActionPerformed
        // TODO add your handling code here:
        // Xoa table
        DefaultTableModel dtm = (DefaultTableModel) jTable_DoanhThu.getModel();
        while(jTable_DoanhThu.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        
        String thang = jTextField_Thang.getText();
        String nam = jTextField_Nam.getText();
        String maNV = jTextField_MaNV.getText();
        String maKH = jTextField_MaKH.getText();
        String maNCC = "";
        if(!jComboBox_NCC.getSelectedItem().toString().equals("")) {
            String[] temp = jComboBox_NCC.getSelectedItem().toString().split("-");
            maNCC = temp[0];
        }
        
        if(thang.equals("") && nam.equals("") && maNV.equals("") && maKH.equals("") && maNCC.equals("")) {
            JOptionPane.showMessageDialog(null, "Hãy nhập một điều kiện tìm kiếm!!!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else {
            List<HoaDon> listHD = new ArrayList<>();
            try {
                String connectionUrl = "jdbc:sqlserver://localhost:1433;DatabaseName=DBComputerStore;user=sa;password=123456;encrypt=true;trustServerCertificate=true";
                Connection con = DriverManager.getConnection(connectionUrl);
                String sql = "SELECT * FROM tblHDban WHERE 1 = 1";
                if(!thang.equals("")) {
                    sql = sql + " AND MONTH(NgayBan) =" + thang;
                }
                if(!nam.equals("")) {
                    sql = sql + " AND YEAR(NgayBan) =" + nam;
                }
                if(!maNV.equals("")) {
                    TaiKhoan tk = TaiKhoan.layTaiKhoan(maNV);
                   sql = sql + " AND MaTK LIKE '%" + tk.getMaTK() +"%'";
                }
                if (!maKH.equals("")) {
                    sql = sql + " AND MaKH LIKE '%" + maKH +"%'";
                }
                if(!maNCC.equals("")) {
                    sql = sql + " AND MaHD IN (''";
                    List<SanPham> listSP = SanPham.sanPhamList();
                    for (int i = 0; i < listSP.size(); i++) {
                        SanPham get = listSP.get(i);
                        if(get.getNhaCC().equals(maNCC)) {
                            String maSP = get.getMaSP();
                            List<ChiTietHoaDon> listCTHD = ChiTietHoaDon.GetChiTietHoaDons(maSP);
                            for (int j = 0; j < listCTHD.size(); j++) {
                                ChiTietHoaDon get1 = listCTHD.get(j);
                                sql = sql + ",'" + get1.getMaHD() + "'";
                            }
                        }
                    }
                    sql = sql + ")";
                }
                PreparedStatement pst = con.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();
                HoaDon hd;
                while(rs.next()) {
                    hd = new HoaDon(rs.getString(1), rs.getString(2), rs.getString(3), rs.getDate(4), rs.getLong(5));
                    listHD.add(hd);
                }
                pst.close();
                con.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            
            if(listHD.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Không có hóa đơn thỏa mãn điều kiện!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                jTextField_TongTien.setText("");
            } else {
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                Object[] os = new Object[8];
                int dem = 1;
                long tongTien = 0;
                for (int i = 0; i < listHD.size(); i++) {
                    HoaDon get = listHD.get(i);
                    List<ChiTietHoaDon> listCTHD = ChiTietHoaDon.ChiTietHoaDonList(get.getMaHD());
                    TaiKhoan tk = TaiKhoan.layTK(get.getMaTK());
                    for (int j = 0; j < listCTHD.size(); j++) {
                        ChiTietHoaDon get1 = listCTHD.get(j);
                        if(maNCC.equals("")) {
                            os[0] = dem++;
                            os[1] = get.getMaHD();
                            os[2] = tk.getTenTK();
                            os[3] = get.getMaKH();
                            os[4] = get1.getMaSP();
                            os[5] = get1.getSoLuong();
                            os[6] = sdf.format(get.getNgayBan());
                            os[7] = get1.getThanhTien();
                            dtm.addRow(os);
                            
                            tongTien += get1.getThanhTien();
                        } else {
                            if(maNCC.equals(SanPham.getNCC(get1.getMaSP()))) {
                                os[0] = dem++;
                                os[1] = get.getMaHD();
                                os[2] = tk.getTenTK();
                                os[3] = get.getMaKH();
                                os[4] = get1.getMaSP();
                                os[5] = get1.getSoLuong();
                                os[6] = sdf.format(get.getNgayBan());
                                os[7] = get1.getThanhTien();
                                dtm.addRow(os);

                                tongTien += get1.getThanhTien();
                            }
                        }
                    }
                }
                jTextField_TongTien.setText(String.valueOf(tongTien));
            }
        }
    }//GEN-LAST:event_jButton_TimKiemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Exit;
    private javax.swing.JButton jButton_LamMoi;
    private javax.swing.JButton jButton_TimKiem;
    private javax.swing.JComboBox<String> jComboBox_NCC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable_DoanhThu;
    private javax.swing.JTextField jTextField_MaKH;
    private javax.swing.JTextField jTextField_MaNV;
    private javax.swing.JTextField jTextField_Nam;
    private javax.swing.JTextField jTextField_Thang;
    private javax.swing.JTextField jTextField_TongTien;
    // End of variables declaration//GEN-END:variables

    private void showDoanhThu(ArrayList<HoaDon> listHD) {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        DefaultTableModel dtm = (DefaultTableModel) jTable_DoanhThu.getModel();
        Object[] os = new Object[8];
        int dem = 1;
        long tongTien = 0;
        for (int i = 0; i < listHD.size(); i++) {
            HoaDon get = listHD.get(i);
            List<ChiTietHoaDon> listCTHD = ChiTietHoaDon.ChiTietHoaDonList(get.getMaHD());
            TaiKhoan tk = TaiKhoan.layTK(get.getMaTK());
            for (int j = 0; j < listCTHD.size(); j++) {
                ChiTietHoaDon get1 = listCTHD.get(j);
                os[0] = dem++;
                os[1] = get.getMaHD();
                os[2] = tk.getTenTK();
                os[3] = get.getMaKH();
                os[4] = get1.getMaSP();
                os[5] = get1.getSoLuong();
                os[6] = sdf.format(get.getNgayBan());
                os[7] = get1.getThanhTien();
                dtm.addRow(os);
                
                tongTien += get1.getThanhTien();
            }
        }
        jTextField_TongTien.setText(String.valueOf(tongTien));
    }

    private void showJComboBox() {
        jComboBox_NCC.addItem("");
        List<String> data = NhaCungCap.tenNCC();
        for (int i = 0; i < data.size(); i++) {
            jComboBox_NCC.addItem(data.get(i));
        }
    }
}
