/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codeptit.QuanLyCuaHangLapTop.View;

import codeptit.QuanLyCuaHangLapTop.Model.ChiTietHoaDon;
import codeptit.QuanLyCuaHangLapTop.Model.HoaDon;
import codeptit.QuanLyCuaHangLapTop.Model.KhachHang;
import codeptit.QuanLyCuaHangLapTop.Model.NhanVien;
import codeptit.QuanLyCuaHangLapTop.Model.SanPham;
import codeptit.QuanLyCuaHangLapTop.Model.TaiKhoan;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class HoaDon_BanView extends javax.swing.JFrame {
    private String tenTK;
    /**
     * Creates new form HoaDonBanView
     */
    public HoaDon_BanView(String tk) {
        this.tenTK = tk;
        initComponents();
        editJText();
        showHoaDon();
        showTaiKhoan();
        showJTable();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel_ThongTinChung = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_MaHD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_NgayBan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_TenNV = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox_MaKH = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField_TenKH = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField_SDT = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jTextField_DiaChi = new javax.swing.JTextField();
        jTextField_MaTK = new javax.swing.JTextField();
        jPanel_ThongTinSP = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField_TenSP = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField_DonGia = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField_SoLuong = new javax.swing.JTextField();
        jTextField_GiamGia = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jComboBox_MaSP = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_DanhSachSP = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jTextField_TongTien = new javax.swing.JTextField();
        jTextField_ThanhTien = new javax.swing.JTextField();
        jButton_ThemSP = new javax.swing.JButton();
        jButton_Sua = new javax.swing.JButton();
        jButton_Xoa = new javax.swing.JButton();
        jButton_LuuHD = new javax.swing.JButton();
        jButton_HuyHD = new javax.swing.JButton();
        jButton_InHD = new javax.swing.JButton();
        jButton_Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Hóa Đơn Bán Hàng");

        jPanel_ThongTinChung.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Thông tin chung");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 204));
        jLabel3.setText("Mã hóa đơn:");

        jTextField_MaHD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_MaHD.setText(" ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 204));
        jLabel4.setText("Ngày bán:");

        jTextField_NgayBan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_NgayBan.setText(" ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 204));
        jLabel5.setText("Mã tài khoản:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 204));
        jLabel6.setText("Tên nhân viên:");

        jTextField_TenNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_TenNV.setText(" ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 204));
        jLabel7.setText("Mã khách hàng:");

        jComboBox_MaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_MaKHActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 204));
        jLabel8.setText("Tên khách hàng:");

        jTextField_TenKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_TenKH.setText(" ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 0, 204));
        jLabel10.setText("Địa chỉ:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 204));
        jLabel11.setText("Số điện thoại:");

        jTextField_SDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_SDT.setText(" ");

        jTextField_DiaChi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_DiaChi.setText(" ");

        jTextField_MaTK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_MaTK.setText(" ");

        javax.swing.GroupLayout jPanel_ThongTinChungLayout = new javax.swing.GroupLayout(jPanel_ThongTinChung);
        jPanel_ThongTinChung.setLayout(jPanel_ThongTinChungLayout);
        jPanel_ThongTinChungLayout.setHorizontalGroup(
            jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ThongTinChungLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ThongTinChungLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_NgayBan, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_TenNV, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_MaHD, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_MaTK, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(125, 125, 125)
                        .addGroup(jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel_ThongTinChungLayout.createSequentialGroup()
                                .addGroup(jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBox_MaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_TenKH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextField_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel_ThongTinChungLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46))
                    .addGroup(jPanel_ThongTinChungLayout.createSequentialGroup()
                        .addGroup(jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel_ThongTinChungLayout.setVerticalGroup(
            jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ThongTinChungLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ThongTinChungLayout.createSequentialGroup()
                        .addGroup(jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_ThongTinChungLayout.createSequentialGroup()
                                .addGroup(jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextField_MaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextField_NgayBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel_ThongTinChungLayout.createSequentialGroup()
                                .addComponent(jComboBox_MaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_TenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_ThongTinChungLayout.createSequentialGroup()
                                .addGroup(jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(jTextField_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel11)))
                            .addGroup(jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jTextField_MaTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_ThongTinSP.setBackground(new java.awt.Color(204, 204, 204));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Thông tin các sản phẩm");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Mã sản phẩm:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Tên sản phẩm:");

        jTextField_TenSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Đơn giá:");

        jTextField_DonGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Số lượng:");

        jTextField_SoLuong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_SoLuong.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_SoLuongFocusLost(evt);
            }
        });
        jTextField_SoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SoLuongActionPerformed(evt);
            }
        });

        jTextField_GiamGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_GiamGia.setText("0");
        jTextField_GiamGia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_GiamGiaFocusLost(evt);
            }
        });
        jTextField_GiamGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_GiamGiaActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Giảm giá(%):");

        jComboBox_MaSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_MaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_MaSPActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Thành tiền:");

        jTable_DanhSachSP = new JTable() {
            public boolean isCellEditable(int row, int column) {
                for(int i = 0; i < jTable_DanhSachSP.getRowCount(); i++) {
                    if(row == i) return false;
                }
                return true;
            }
        };
        jTable_DanhSachSP.setBackground(new java.awt.Color(255, 153, 153));
        jTable_DanhSachSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Đơn giá", "Giảm giá(%)", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Long.class, java.lang.Integer.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_DanhSachSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_DanhSachSPMouseClicked(evt);
            }
        });
        jTable_DanhSachSP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable_DanhSachSPKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_DanhSachSP);
        if (jTable_DanhSachSP.getColumnModel().getColumnCount() > 0) {
            jTable_DanhSachSP.getColumnModel().getColumn(0).setMinWidth(35);
            jTable_DanhSachSP.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTable_DanhSachSP.getColumnModel().getColumn(0).setMaxWidth(50);
            jTable_DanhSachSP.getColumnModel().getColumn(1).setMinWidth(90);
            jTable_DanhSachSP.getColumnModel().getColumn(1).setPreferredWidth(0);
            jTable_DanhSachSP.getColumnModel().getColumn(1).setMaxWidth(140);
            jTable_DanhSachSP.getColumnModel().getColumn(3).setMinWidth(100);
            jTable_DanhSachSP.getColumnModel().getColumn(3).setPreferredWidth(0);
            jTable_DanhSachSP.getColumnModel().getColumn(3).setMaxWidth(120);
            jTable_DanhSachSP.getColumnModel().getColumn(4).setMinWidth(100);
            jTable_DanhSachSP.getColumnModel().getColumn(4).setPreferredWidth(0);
            jTable_DanhSachSP.getColumnModel().getColumn(4).setMaxWidth(120);
            jTable_DanhSachSP.getColumnModel().getColumn(5).setMinWidth(100);
            jTable_DanhSachSP.getColumnModel().getColumn(5).setPreferredWidth(0);
            jTable_DanhSachSP.getColumnModel().getColumn(5).setMaxWidth(120);
            jTable_DanhSachSP.getColumnModel().getColumn(6).setMinWidth(100);
            jTable_DanhSachSP.getColumnModel().getColumn(6).setPreferredWidth(0);
            jTable_DanhSachSP.getColumnModel().getColumn(6).setMaxWidth(120);
        }

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText("Tổng tiền:");

        jTextField_TongTien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_TongTien.setText("0");

        jTextField_ThanhTien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_ThanhTien.setText("0");

        javax.swing.GroupLayout jPanel_ThongTinSPLayout = new javax.swing.GroupLayout(jPanel_ThongTinSP);
        jPanel_ThongTinSP.setLayout(jPanel_ThongTinSPLayout);
        jPanel_ThongTinSPLayout.setHorizontalGroup(
            jPanel_ThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ThongTinSPLayout.createSequentialGroup()
                .addGroup(jPanel_ThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ThongTinSPLayout.createSequentialGroup()
                        .addGroup(jPanel_ThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_ThongTinSPLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel_ThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel_ThongTinSPLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel_ThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_ThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox_MaSP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField_TenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_ThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_ThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_GiamGia, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(jTextField_SoLuong))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_ThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_ThongTinSPLayout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(36, 36, 36)
                                        .addComponent(jTextField_DonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel_ThongTinSPLayout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField_ThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_ThongTinSPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_ThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ThongTinSPLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel_ThongTinSPLayout.setVerticalGroup(
            jPanel_ThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ThongTinSPLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel9)
                .addGap(2, 2, 2)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel_ThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jTextField_DonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_MaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_ThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField_GiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField_TenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField_ThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_ThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton_ThemSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_ThemSP.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\math-add-icon.png")); // NOI18N
        jButton_ThemSP.setText("Thêm");
        jButton_ThemSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemSPActionPerformed(evt);
            }
        });

        jButton_Sua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Sua.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\edit-icon.png")); // NOI18N
        jButton_Sua.setText("Sửa");
        jButton_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SuaActionPerformed(evt);
            }
        });

        jButton_Xoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Xoa.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\Close-2-icon.png")); // NOI18N
        jButton_Xoa.setText("Xóa");
        jButton_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XoaActionPerformed(evt);
            }
        });

        jButton_LuuHD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_LuuHD.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\Save-icon.png")); // NOI18N
        jButton_LuuHD.setText("Lưu hóa đơn");
        jButton_LuuHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LuuHDActionPerformed(evt);
            }
        });

        jButton_HuyHD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_HuyHD.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\delete-file-icon.png")); // NOI18N
        jButton_HuyHD.setText("Hủy hóa đơn");
        jButton_HuyHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HuyHDActionPerformed(evt);
            }
        });

        jButton_InHD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_InHD.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\print-icon.png")); // NOI18N
        jButton_InHD.setText("In hóa đơn");
        jButton_InHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InHDActionPerformed(evt);
            }
        });

        jButton_Exit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Exit.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\Button-Close-icon.png")); // NOI18N
        jButton_Exit.setText("Thoát");
        jButton_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel_ThongTinChung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel_ThongTinSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel1))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(197, 197, 197))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_ThemSP)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jButton_Sua)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Xoa)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_LuuHD)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_HuyHD)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_InHD)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Exit)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_ThongTinChung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_ThongTinSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_ThemSP)
                    .addComponent(jButton_Sua)
                    .addComponent(jButton_Xoa)
                    .addComponent(jButton_LuuHD)
                    .addComponent(jButton_HuyHD)
                    .addComponent(jButton_InHD)
                    .addComponent(jButton_Exit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_LuuHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LuuHDActionPerformed
        if(jComboBox_MaKH.getSelectedItem().toString().equals("") || jTable_DanhSachSP.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Thông tin hóa đơn chưa đầy đủ!", "Lỗi dữ liệu", JOptionPane.ERROR_MESSAGE);
        } else {
            String maHD = jTextField_MaHD.getText();

            // Nhap hoa don
            try {
                String maTK = jTextField_MaTK.getText();
                String maKH = jComboBox_MaKH.getSelectedItem().toString();
                Date ngayBan = new SimpleDateFormat("dd/MM/yyyy").parse(jTextField_NgayBan.getText());
                long tongTien = Long.valueOf(jTextField_TongTien.getText());
                HoaDon hd = new HoaDon(maHD, maTK, maKH, ngayBan, tongTien);
                hd.nhapHoaDon();
            } catch (ParseException ex) {
                Logger.getLogger(HoaDon_BanView.class.getName()).log(Level.SEVERE, null, ex);
            }

            // Nhap chi tiet hoa don
            DefaultTableModel dtm = (DefaultTableModel) jTable_DanhSachSP.getModel();
            for (int i = 0; i < jTable_DanhSachSP.getRowCount(); i++) {
                String maSP = dtm.getValueAt(i, 1).toString();
                int soLuong = Integer.valueOf(dtm.getValueAt(i, 3).toString());
                long donGia = Long.valueOf(dtm.getValueAt(i, 4).toString());
                int giamGia = Integer.valueOf(dtm.getValueAt(i, 5).toString());
                long thanhTien = Long.valueOf(dtm.getValueAt(i, 6).toString());
                ChiTietHoaDon cthd = new ChiTietHoaDon(maHD, maSP, soLuong, donGia, giamGia, thanhTien);
                cthd.nhapChiTietHoaDon();
                
                // Sua so luong san pham
                SanPham.suaSoLuongSP(maSP, soLuong);
            }
            
            JOptionPane.showMessageDialog(null, "Lưu hóa đơn thành công!", "Thành công!", JOptionPane.INFORMATION_MESSAGE);
            jButton_InHD.setEnabled(true);
        }
        
    }//GEN-LAST:event_jButton_LuuHDActionPerformed

    private void jButton_HuyHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HuyHDActionPerformed
        // TODO add your handling code here:
        // Reset du lieu:
        DefaultTableModel dtm = (DefaultTableModel) jTable_DanhSachSP.getModel();
        showHoaDon();
        jComboBox_MaKH.setSelectedIndex(0);
        jComboBox_MaSP.setSelectedIndex(0);
        jTextField_SoLuong.setText("");
        jTextField_GiamGia.setText("0");
        jTextField_TongTien.setText("0");
        while(jTable_DanhSachSP.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        JOptionPane.showMessageDialog(null, "Hủy hóa đơn thành công!", "Thành công!", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton_HuyHDActionPerformed

    private void jButton_InHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InHDActionPerformed
        HoaDon_ChiTietView cthdv = new HoaDon_ChiTietView(jTextField_MaHD.getText());
        cthdv.InHoaDon();
        
        // Reset du lieu:
        DefaultTableModel dtm = (DefaultTableModel) jTable_DanhSachSP.getModel();
        showHoaDon();
        jComboBox_MaKH.setSelectedIndex(0);
        jComboBox_MaSP.setSelectedIndex(0);
        jTextField_SoLuong.setText("");
        jTextField_GiamGia.setText("0");
        jTextField_TongTien.setText("0");
        while(jTable_DanhSachSP.getRowCount() > 0) {
            dtm.removeRow(0);
        }
    }//GEN-LAST:event_jButton_InHDActionPerformed

    private void jButton_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton_ExitActionPerformed

    private void jComboBox_MaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_MaKHActionPerformed
        // TODO add your handling code here:
        List<KhachHang> khachList = KhachHang.khachList();
        String maKH = (String) jComboBox_MaKH.getSelectedItem();
        if(maKH.equals("")) {
            jTextField_TenKH.setText("");
            jTextField_DiaChi.setText("");
            jTextField_SDT.setText("");
        } else {
            for (int i = 0; i < khachList.size(); i++) {
                String ma = khachList.get(i).getMaKH();
                if(ma.equals(maKH)) {
                    jTextField_TenKH.setText(khachList.get(i).getTenKH());
                    jTextField_DiaChi.setText(khachList.get(i).getDiaChi());
                    jTextField_SDT.setText(khachList.get(i).getDienThoai());
                    break;
                }
            }
        }
    }//GEN-LAST:event_jComboBox_MaKHActionPerformed

    private void jComboBox_MaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_MaSPActionPerformed
        // TODO add your handling code here:
        List<SanPham> sanPhamList = SanPham.sanPhamList();
        String maSP = (String) jComboBox_MaSP.getSelectedItem();
        if(maSP.equals("")) {
            jTextField_TenSP.setText("");
            jTextField_DonGia.setText("");
            jTextField_SoLuong.setText("");
            jTextField_GiamGia.setText("0");
            jTextField_ThanhTien.setText("0");
        } else {
            for (int i = 0; i < sanPhamList.size(); i++) {
                String ma = sanPhamList.get(i).getMaSP();
                if(ma.equals(maSP)) {
                    jTextField_TenSP.setText(sanPhamList.get(i).getTenSP());
                    jTextField_DonGia.setText(String.valueOf(sanPhamList.get(i).getGiaBan()));
                    jTextField_SoLuong.setText("1");
                    jTextField_GiamGia.setText("0");
                    jTextField_ThanhTien.setText(String.valueOf(sanPhamList.get(i).getGiaBan()));
                    break;
                }
            }
        }
    }//GEN-LAST:event_jComboBox_MaSPActionPerformed

    private void jTextField_SoLuongFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_SoLuongFocusLost
        // TODO add your handling code here:
        int soLuong = Integer.valueOf(jTextField_SoLuong.getText());
        int giamGia = Integer.valueOf(jTextField_GiamGia.getText());
        if(soLuong <= 0) {
            jTextField_ThanhTien.setText("0");
            JOptionPane.showMessageDialog(null, "Vui lòng nhập lại dữ liệu thích hợp!", "Dữ liệu không hợp lệ", JOptionPane.ERROR_MESSAGE);
        } else if(giamGia >= 0) {
            long donBan = Long.valueOf(jTextField_DonGia.getText());
            Long thanhTien = soLuong * donBan * (100 - giamGia) / 100;
            jTextField_ThanhTien.setText(String.valueOf(thanhTien));
        }
    }//GEN-LAST:event_jTextField_SoLuongFocusLost

    private void jTextField_GiamGiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_GiamGiaFocusLost
        // TODO add your handling code here:
        int soLuong = Integer.valueOf(jTextField_SoLuong.getText());
        int giamGia = Integer.valueOf(jTextField_GiamGia.getText());
        if(giamGia < 0) {
            jTextField_ThanhTien.setText("0");
            JOptionPane.showMessageDialog(null, "Vui lòng nhập lại dữ liệu thích hợp!", "Dữ liệu không hợp lệ", JOptionPane.ERROR_MESSAGE);
        } else if(soLuong > 0) {
            long donBan = Long.valueOf(jTextField_DonGia.getText());
            Long thanhTien = soLuong * donBan * (100 - giamGia) / 100;
            jTextField_ThanhTien.setText(String.valueOf(thanhTien));
        }
    }//GEN-LAST:event_jTextField_GiamGiaFocusLost

    private void jTextField_SoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SoLuongActionPerformed
        // TODO add your handling code here:
        int soLuong = Integer.valueOf(jTextField_SoLuong.getText());
        int giamGia = Integer.valueOf(jTextField_GiamGia.getText());
        if(soLuong <= 0) {
            jTextField_ThanhTien.setText("0");
            JOptionPane.showMessageDialog(null, "Vui lòng nhập lại dữ liệu thích hợp!", "Dữ liệu không hợp lệ", JOptionPane.ERROR_MESSAGE);
        } else if(giamGia >= 0) {
            long donBan = Long.valueOf(jTextField_DonGia.getText());
            Long thanhTien = soLuong * donBan * (100 - giamGia) / 100;
            jTextField_ThanhTien.setText(String.valueOf(thanhTien));
        }
    }//GEN-LAST:event_jTextField_SoLuongActionPerformed

    private void jTextField_GiamGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_GiamGiaActionPerformed
        // TODO add your handling code here:
        int soLuong = Integer.valueOf(jTextField_SoLuong.getText());
        int giamGia = Integer.valueOf(jTextField_GiamGia.getText());
        if(giamGia < 0) {
            jTextField_ThanhTien.setText("0");
            JOptionPane.showMessageDialog(null, "Vui lòng nhập lại dữ liệu thích hợp!", "Dữ liệu không hợp lệ", JOptionPane.ERROR_MESSAGE);
        } else if(soLuong > 0) {
            long donBan = Long.valueOf(jTextField_DonGia.getText());
            Long thanhTien = soLuong * donBan * (100 - giamGia) / 100;
            jTextField_ThanhTien.setText(String.valueOf(thanhTien));
        }
    }//GEN-LAST:event_jTextField_GiamGiaActionPerformed

    private void jButton_ThemSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemSPActionPerformed
        // TODO add your handling code here:
        if(jComboBox_MaSP.getSelectedItem().equals("") || jTextField_SoLuong.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập lại dữ liệu thích hợp!", "Dữ liệu không hợp lệ", JOptionPane.ERROR_MESSAGE);
        } else {
            String maSP = jComboBox_MaSP.getSelectedItem().toString();
            int SL = Integer.valueOf(jTextField_SoLuong.getText());
            if(SL <= SanPham.getSoLuong(maSP)) {
                DefaultTableModel dtm = (DefaultTableModel) jTable_DanhSachSP.getModel();
                Object[] os = new Object[7];
                os[0] = dtm.getRowCount() + 1;
                os[1] = jComboBox_MaSP.getSelectedItem();
                os[2] = jTextField_TenSP.getText();
                os[3] = jTextField_SoLuong.getText();
                os[4] = jTextField_DonGia.getText();
                os[5] = jTextField_GiamGia.getText();
                os[6] = jTextField_ThanhTien.getText();
                dtm.addRow(os);
                // Tinh tong tien
                long tongTien = Long.valueOf(jTextField_ThanhTien.getText()) + Long.valueOf(jTextField_TongTien.getText());
                jTextField_TongTien.setText(String.valueOf(tongTien));
                JOptionPane.showMessageDialog(null, "Thêm sản phẩm thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Vui lòng kiểm tra lại số lượng sản phẩm!", "Sản phẩm không còn đủ!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton_ThemSPActionPerformed

    private void jTable_DanhSachSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_DanhSachSPMouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable_DanhSachSP.getSelectedRow();
        DefaultTableModel dtm = (DefaultTableModel) jTable_DanhSachSP.getModel();
        jComboBox_MaSP.setSelectedItem(dtm.getValueAt(selectedRow, 1).toString());
        jTextField_SoLuong.setText(dtm.getValueAt(selectedRow, 3).toString());
        jTextField_GiamGia.setText(dtm.getValueAt(selectedRow, 5).toString());
        jTextField_ThanhTien.setText(dtm.getValueAt(selectedRow, 6).toString());
    }//GEN-LAST:event_jTable_DanhSachSPMouseClicked

    private void jButton_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XoaActionPerformed
        // TODO add your handling code here:
        if(jTable_DanhSachSP.getSelectedRowCount() == 1) {
            int selectedRow = jTable_DanhSachSP.getSelectedRow();
            DefaultTableModel dtm = (DefaultTableModel) jTable_DanhSachSP.getModel();
            long thanhTien = Long.valueOf(jTextField_ThanhTien.getText());
            long tongTien = Long.valueOf(jTextField_TongTien.getText());
            jTextField_TongTien.setText(String.valueOf(tongTien - thanhTien));
            dtm.removeRow(selectedRow);
            jComboBox_MaSP.setSelectedIndex(0);
            jTextField_SoLuong.setText("");
            jTextField_GiamGia.setText("0");
            JOptionPane.showMessageDialog(null, "Đã xóa sản phẩm thành công!", "Thực hiện thành công", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if(jTable_DanhSachSP.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Bảng không có dữ liệu!", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Hay chọn từng cột để xóa!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        
    }//GEN-LAST:event_jButton_XoaActionPerformed

    private void jButton_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SuaActionPerformed
        // TODO add your handling code here:
        if(jTable_DanhSachSP.getSelectedRowCount() == 1) {
            String maSP = jComboBox_MaSP.getSelectedItem().toString();
            String tenSP = jTextField_TenSP.getText();
            String soLuong = jTextField_SoLuong.getText();
            String donGia = jTextField_DonGia.getText();
            String giamGia = jTextField_GiamGia.getText();
            String thanhTien = jTextField_ThanhTien.getText();
            
            // Sua bang
            int selectedRow = jTable_DanhSachSP.getSelectedRow();
            DefaultTableModel dtm = (DefaultTableModel) jTable_DanhSachSP.getModel();
            dtm.setValueAt(maSP, selectedRow, 1);
            dtm.setValueAt(tenSP, selectedRow, 2);
            dtm.setValueAt(soLuong, selectedRow, 3);
            dtm.setValueAt(donGia, selectedRow, 4);
            dtm.setValueAt(giamGia, selectedRow, 5);
            dtm.setValueAt(thanhTien, selectedRow, 6);
            JOptionPane.showMessageDialog(null, "Đã sửa danh sách sản phẩm thành công!", "Thực hiện thành công", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if(jTable_DanhSachSP.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Bảng không có dữ liệu!", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Hay chọn từng cột để sửa!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton_SuaActionPerformed

    private void jTable_DanhSachSPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable_DanhSachSPKeyReleased
        // TODO add your handling code here:
        int selectedRow = jTable_DanhSachSP.getSelectedRow();
        DefaultTableModel dtm = (DefaultTableModel) jTable_DanhSachSP.getModel();
        jComboBox_MaSP.setSelectedItem(dtm.getValueAt(selectedRow, 1).toString());
        jTextField_SoLuong.setText(dtm.getValueAt(selectedRow, 3).toString());
        jTextField_GiamGia.setText(dtm.getValueAt(selectedRow, 5).toString());
    }//GEN-LAST:event_jTable_DanhSachSPKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Exit;
    private javax.swing.JButton jButton_HuyHD;
    private javax.swing.JButton jButton_InHD;
    private javax.swing.JButton jButton_LuuHD;
    private javax.swing.JButton jButton_Sua;
    private javax.swing.JButton jButton_ThemSP;
    private javax.swing.JButton jButton_Xoa;
    private javax.swing.JComboBox<String> jComboBox_MaKH;
    private javax.swing.JComboBox<String> jComboBox_MaSP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_ThongTinChung;
    private javax.swing.JPanel jPanel_ThongTinSP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable_DanhSachSP;
    private javax.swing.JTextField jTextField_DiaChi;
    private javax.swing.JTextField jTextField_DonGia;
    private javax.swing.JTextField jTextField_GiamGia;
    private javax.swing.JTextField jTextField_MaHD;
    private javax.swing.JTextField jTextField_MaTK;
    private javax.swing.JTextField jTextField_NgayBan;
    private javax.swing.JTextField jTextField_SDT;
    private javax.swing.JTextField jTextField_SoLuong;
    private javax.swing.JTextField jTextField_TenKH;
    private javax.swing.JTextField jTextField_TenNV;
    private javax.swing.JTextField jTextField_TenSP;
    private javax.swing.JTextField jTextField_ThanhTien;
    private javax.swing.JTextField jTextField_TongTien;
    // End of variables declaration//GEN-END:variables

    private void editJText() {
        jTextField_MaHD.setEditable(false);
        jTextField_NgayBan.setEditable(false);
        jTextField_MaTK.setEditable(false);
        jTextField_TenNV.setEditable(false);
        jTextField_TenKH.setEditable(false);
        jTextField_DiaChi.setEditable(false);
        jTextField_SDT.setEditable(false);
        jTextField_TenSP.setEditable(false);
        jTextField_DonGia.setEditable(false);
        jTextField_ThanhTien.setEditable(false);
        jTextField_TongTien.setEditable(false);
        jButton_InHD.setEnabled(false);
    }

    private void showJTable() {
        // Them khach hang
        List<KhachHang> khachList = KhachHang.khachList();
        jComboBox_MaKH.addItem("");
        for (int i = 0; i < khachList.size(); i++) {
            jComboBox_MaKH.addItem(khachList.get(i).getMaKH());
        }
        // Them san pham
        List<SanPham> sanPhamList = SanPham.sanPhamList();
        jComboBox_MaSP.addItem("");
        for (int i = 0; i < sanPhamList.size(); i++) {
            jComboBox_MaSP.addItem(sanPhamList.get(i).getMaSP());
        }
    }

    private void showHoaDon() {
        // Hien thi ma hoa don va ngay tao hoa don
        List<HoaDon> hoaDonList = HoaDon.hoaDonList();
        String maHD;
        if(hoaDonList.isEmpty()) {
            maHD = "001";
        } else {
            String ma = hoaDonList.get(hoaDonList.size()-1).getMaHD();
            int soLuong = Integer.valueOf(ma.substring(3,ma.length())) + 1;
            maHD = String.valueOf(soLuong);
            while (maHD.length() < 3) maHD = "0" + maHD;
        }
        jTextField_MaHD.setText("HD" + maHD);
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Date ngayBan = new Date();
        jTextField_NgayBan.setText(sdf.format(ngayBan));
    }

    private void showTaiKhoan() {
        List<NhanVien> nhanVienList = NhanVien.nhanVienList();
        TaiKhoan tk = TaiKhoan.layTaiKhoan(tenTK);
        jTextField_MaTK.setText(tk.getMaTK());
        String tenTK = tk.getTenTK();
        for (int i = 0; i < nhanVienList.size(); i++) {
            String maNV = nhanVienList.get(i).getMaNV();
            if(maNV.equals(tenTK)) {
                jTextField_TenNV.setText(nhanVienList.get(i).getTenNV());
                break;
            }
        }
    }
}
