/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codeptit.QuanLyCuaHangLapTop.View;

import codeptit.QuanLyCuaHangLapTop.Model.ChiTietHoaDon;
import codeptit.QuanLyCuaHangLapTop.Model.HoaDon;
import codeptit.QuanLyCuaHangLapTop.Model.KhachHang;
import codeptit.QuanLyCuaHangLapTop.Model.NhanVien;
import codeptit.QuanLyCuaHangLapTop.Model.SanPham;
import codeptit.QuanLyCuaHangLapTop.Model.TaiKhoan;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class HoaDon_ChiTietView extends javax.swing.JFrame {
    String maHD;
    /**
     * Creates new form ChiTietHoaDonView
     * @param maHD
     */
    public HoaDon_ChiTietView(String maHD) {
        this.maHD = maHD; 
        initComponents();
        editJtext();
        showTTChung();
        showTTSanPham();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_HoaDon = new javax.swing.JPanel();
        jPanel_ThongTinSP = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_DanhSachSP = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jTextField_TongTien = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel_ThongTinChung = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_MaHD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_NgayBan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_TenNV = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_TenKH = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField_SDT = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jTextField_DiaChi = new javax.swing.JTextField();
        jTextField_MaTK = new javax.swing.JTextField();
        jTextField_MaKH = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel_ThongTinSP.setBackground(new java.awt.Color(204, 204, 204));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Thông tin các sản phẩm");

        jTable_DanhSachSP = new JTable() {
            public boolean isCellEditable(int row, int column) {
                for(int i = 0; i < jTable_DanhSachSP.getRowCount(); i++) {
                    if(row == i) return false;
                }
                return true;
            }
        };
        jTable_DanhSachSP.setBackground(new java.awt.Color(255, 153, 153));
        jTable_DanhSachSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Đơn giá", "Giảm giá(%)", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Long.class, java.lang.Integer.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_DanhSachSP);
        if (jTable_DanhSachSP.getColumnModel().getColumnCount() > 0) {
            jTable_DanhSachSP.getColumnModel().getColumn(0).setMinWidth(35);
            jTable_DanhSachSP.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTable_DanhSachSP.getColumnModel().getColumn(0).setMaxWidth(50);
            jTable_DanhSachSP.getColumnModel().getColumn(1).setMinWidth(90);
            jTable_DanhSachSP.getColumnModel().getColumn(1).setPreferredWidth(0);
            jTable_DanhSachSP.getColumnModel().getColumn(1).setMaxWidth(140);
            jTable_DanhSachSP.getColumnModel().getColumn(3).setMinWidth(90);
            jTable_DanhSachSP.getColumnModel().getColumn(3).setPreferredWidth(0);
            jTable_DanhSachSP.getColumnModel().getColumn(3).setMaxWidth(120);
            jTable_DanhSachSP.getColumnModel().getColumn(4).setMinWidth(90);
            jTable_DanhSachSP.getColumnModel().getColumn(4).setPreferredWidth(0);
            jTable_DanhSachSP.getColumnModel().getColumn(4).setMaxWidth(120);
            jTable_DanhSachSP.getColumnModel().getColumn(5).setMinWidth(90);
            jTable_DanhSachSP.getColumnModel().getColumn(5).setPreferredWidth(0);
            jTable_DanhSachSP.getColumnModel().getColumn(5).setMaxWidth(120);
            jTable_DanhSachSP.getColumnModel().getColumn(6).setMinWidth(90);
            jTable_DanhSachSP.getColumnModel().getColumn(6).setPreferredWidth(0);
            jTable_DanhSachSP.getColumnModel().getColumn(6).setMaxWidth(120);
        }

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText("Tổng tiền:");

        jTextField_TongTien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_TongTien.setText("0");

        javax.swing.GroupLayout jPanel_ThongTinSPLayout = new javax.swing.GroupLayout(jPanel_ThongTinSP);
        jPanel_ThongTinSP.setLayout(jPanel_ThongTinSPLayout);
        jPanel_ThongTinSPLayout.setHorizontalGroup(
            jPanel_ThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ThongTinSPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ThongTinSPLayout.createSequentialGroup()
                        .addGroup(jPanel_ThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ThongTinSPLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel_ThongTinSPLayout.setVerticalGroup(
            jPanel_ThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ThongTinSPLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel9)
                .addGap(2, 2, 2)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Hóa Đơn Bán Hàng");

        jPanel_ThongTinChung.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Thông tin chung");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 204));
        jLabel3.setText("Mã hóa đơn:");

        jTextField_MaHD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_MaHD.setText(" ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 204));
        jLabel4.setText("Ngày bán:");

        jTextField_NgayBan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_NgayBan.setText(" ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 204));
        jLabel5.setText("Mã tài khoản:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 204));
        jLabel6.setText("Tên nhân viên:");

        jTextField_TenNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_TenNV.setText(" ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 204));
        jLabel7.setText("Mã khách hàng:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 204));
        jLabel8.setText("Tên khách hàng:");

        jTextField_TenKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_TenKH.setText(" ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 0, 204));
        jLabel10.setText("Địa chỉ:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 204));
        jLabel11.setText("Số điện thoại:");

        jTextField_SDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_SDT.setText(" ");

        jTextField_DiaChi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_DiaChi.setText(" ");

        jTextField_MaTK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_MaTK.setText(" ");

        jTextField_MaKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_MaKH.setText(" ");

        javax.swing.GroupLayout jPanel_ThongTinChungLayout = new javax.swing.GroupLayout(jPanel_ThongTinChung);
        jPanel_ThongTinChung.setLayout(jPanel_ThongTinChungLayout);
        jPanel_ThongTinChungLayout.setHorizontalGroup(
            jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ThongTinChungLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ThongTinChungLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField_MaTK, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(jTextField_NgayBan, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_MaHD, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_TenNV)))
                    .addComponent(jLabel2)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel_ThongTinChungLayout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(85, 85, 85)
                            .addComponent(jTextField_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel_ThongTinChungLayout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel_ThongTinChungLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(26, 26, 26)
                            .addComponent(jTextField_TenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ThongTinChungLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_MaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46))
        );
        jPanel_ThongTinChungLayout.setVerticalGroup(
            jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ThongTinChungLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_ThongTinChungLayout.createSequentialGroup()
                        .addGroup(jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField_MaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField_NgayBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_ThongTinChungLayout.createSequentialGroup()
                        .addGroup(jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_MaKH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_TenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ThongTinChungLayout.createSequentialGroup()
                        .addGroup(jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jTextField_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11)))
                    .addGroup(jPanel_ThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jTextField_MaTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_HoaDonLayout = new javax.swing.GroupLayout(jPanel_HoaDon);
        jPanel_HoaDon.setLayout(jPanel_HoaDonLayout);
        jPanel_HoaDonLayout.setHorizontalGroup(
            jPanel_HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_ThongTinSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_ThongTinChung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_HoaDonLayout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addGroup(jPanel_HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_HoaDonLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        jPanel_HoaDonLayout.setVerticalGroup(
            jPanel_HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_HoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_ThongTinChung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel_ThongTinSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_HoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_HoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel_HoaDon;
    private javax.swing.JPanel jPanel_ThongTinChung;
    private javax.swing.JPanel jPanel_ThongTinSP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable_DanhSachSP;
    private javax.swing.JTextField jTextField_DiaChi;
    private javax.swing.JTextField jTextField_MaHD;
    private javax.swing.JTextField jTextField_MaKH;
    private javax.swing.JTextField jTextField_MaTK;
    private javax.swing.JTextField jTextField_NgayBan;
    private javax.swing.JTextField jTextField_SDT;
    private javax.swing.JTextField jTextField_TenKH;
    private javax.swing.JTextField jTextField_TenNV;
    private javax.swing.JTextField jTextField_TongTien;
    // End of variables declaration//GEN-END:variables
  
    private void showTTChung() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        HoaDon hd = HoaDon.layHoaDon(maHD);
        jTextField_MaHD.setText(hd.getMaHD());
        jTextField_NgayBan.setText(sdf.format(hd.getNgayBan()));
        jTextField_MaTK.setText(hd.getMaTK());
        jTextField_MaKH.setText(hd.getMaKH());
        jTextField_TongTien.setText(String.valueOf(hd.getTongTien()));
        
        // lay du lieu nhan vien
        List<NhanVien> nhanVienList = NhanVien.nhanVienList();
        TaiKhoan tk = TaiKhoan.layTK(hd.getMaTK());
        String tenTK = tk.getTenTK();
        for (int i = 0; i < nhanVienList.size(); i++) {
            String maNV = nhanVienList.get(i).getMaNV();
            if(maNV.equals(tenTK)) {
                jTextField_TenNV.setText(nhanVienList.get(i).getTenNV());
                break;
            }
        }
        
        // lay du lieu khach hang
        List<KhachHang> khachList = KhachHang.khachList();
        for (int i = 0; i < khachList.size(); i++) {
            String ma = khachList.get(i).getMaKH();
            if(ma.equals(hd.getMaKH())) {
                jTextField_TenKH.setText(khachList.get(i).getTenKH());
                jTextField_DiaChi.setText(khachList.get(i).getDiaChi());
                jTextField_SDT.setText(khachList.get(i).getDienThoai());
                break;
            }
        }
    }

    private void showTTSanPham() {
        List<ChiTietHoaDon> list = ChiTietHoaDon.ChiTietHoaDonList(maHD);
        DefaultTableModel dtm = (DefaultTableModel) jTable_DanhSachSP.getModel();
        Object[] os = new Object[7];
        int stt = 1;
        for (int i = 0; i < list.size(); i++) {
            ChiTietHoaDon get = list.get(i);
            os[0] = stt++;
            os[1] = get.getMaSP();
            os[2] = SanPham.getTenSP(get.getMaSP());
            os[3] = get.getSoLuong();
            os[4] = get.getDonGia();
            os[5] = get.getGiamGia();
            os[6] = get.getThanhTien();
            dtm.addRow(os);
        }
    }
    
    private void editJtext() {
        jTextField_MaHD.setEditable(false);
        jTextField_NgayBan.setEditable(false);
        jTextField_MaTK.setEditable(false);
        jTextField_TenNV.setEditable(false);
        jTextField_MaKH.setEditable(false);
        jTextField_TenKH.setEditable(false);
        jTextField_DiaChi.setEditable(false);
        jTextField_SDT.setEditable(false);
        jTable_DanhSachSP.setEnabled(false);
    }
    
    public void InHoaDon(){
        PrinterJob pj = PrinterJob.getPrinterJob();
        pj.setJobName(" In Hóa Đơn ");

        pj.setPrintable ((Graphics pg, PageFormat pf, int pageNum) -> {
            if (pageNum > 0){
                return Printable.NO_SUCH_PAGE;
            }

            Graphics2D g2 = (Graphics2D) pg;
            g2.translate(pf.getImageableX(), pf.getImageableY());
            jPanel_HoaDon.paint(g2);
            return Printable.PAGE_EXISTS;
        });
        if (pj.printDialog() == false)
            return;

        try {
            pj.print();
        } catch (PrinterException ex) {
            
        }
    }
}
