/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codeptit.QuanLyCuaHangLapTop.View;

import codeptit.QuanLyCuaHangLapTop.Model.KhachHang;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Khach_DanhMucView extends javax.swing.JFrame {
    private ArrayList<KhachHang> list;
    private int listSize;
    private List<String> maXoa;
    static int soMKH;
    /**
     * Creates new form DanhMucKHView
     */
    public Khach_DanhMucView() {
        this.list = KhachHang.khachList();
        maXoa = new ArrayList<>();
        listSize = list.size();
        if(list.isEmpty()) {
            soMKH = 0;
        } else {
            soMKH = Integer.valueOf(list.get(list.size()-1).getMaKH().substring(2,5));
        }
        initComponents();
        showKhach(list);
        jTextField_MaKH.setEditable(false);
        jButton_Luu.setEnabled(false);
    }
    
    public static void showKhach(ArrayList<KhachHang> list) {
        DefaultTableModel dtm = (DefaultTableModel) jTable_KhachHang.getModel();
        while (dtm.getRowCount() > 0) {            
            dtm.removeRow(0);
        }
        Object[] os = new Object[5];
        for (int i = 0; i < list.size(); i++) {
            os[0] = i+1;
            os[1] = list.get(i).getMaKH();
            os[2] = list.get(i).getTenKH();
            os[3] = list.get(i).getDiaChi();
            os[4] = list.get(i).getDienThoai();
            dtm.addRow(os);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_MaKH = new javax.swing.JTextField();
        jTextField_TenKH = new javax.swing.JTextField();
        jTextField_DiaChiKH = new javax.swing.JTextField();
        jTextField_SDTKH = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_KhachHang = new javax.swing.JTable();
        jButton_Them = new javax.swing.JButton();
        jButton_Xoa = new javax.swing.JButton();
        jButton_Sua = new javax.swing.JButton();
        jButton_Luu = new javax.swing.JButton();
        jButton_Exit = new javax.swing.JButton();
        jButton_TimKiem = new javax.swing.JButton();
        jButton_LamMoi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Danh Mục Khách Hàng");
        setBackground(new java.awt.Color(255, 0, 0));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Danh Mục Khách Hàng");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("Tên khách:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 153));
        jLabel4.setText("Địa chỉ:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 153));
        jLabel5.setText("Số điện thoại: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 153));
        jLabel6.setText("Mã khách:");

        jTextField_MaKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField_TenKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField_DiaChiKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField_SDTKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTable_KhachHang = new JTable() {
            public boolean isCellEditable(int row, int column) {
                for(int i = 0; i < jTable_KhachHang.getRowCount(); i++) {
                    if(row == i) return false;
                }
                return true;
            }
        };
        jTable_KhachHang.setBackground(new java.awt.Color(255, 153, 255));
        jTable_KhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã khách", "Tên khách", "Địa chỉ", "Số điện thoại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_KhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_KhachHangMouseClicked(evt);
            }
        });
        jTable_KhachHang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable_KhachHangKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_KhachHang);
        if (jTable_KhachHang.getColumnModel().getColumnCount() > 0) {
            jTable_KhachHang.getColumnModel().getColumn(0).setMinWidth(35);
            jTable_KhachHang.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTable_KhachHang.getColumnModel().getColumn(0).setMaxWidth(50);
            jTable_KhachHang.getColumnModel().getColumn(1).setMinWidth(65);
            jTable_KhachHang.getColumnModel().getColumn(1).setPreferredWidth(0);
            jTable_KhachHang.getColumnModel().getColumn(1).setMaxWidth(70);
            jTable_KhachHang.getColumnModel().getColumn(2).setMinWidth(135);
            jTable_KhachHang.getColumnModel().getColumn(2).setPreferredWidth(0);
            jTable_KhachHang.getColumnModel().getColumn(2).setMaxWidth(150);
            jTable_KhachHang.getColumnModel().getColumn(4).setMinWidth(90);
            jTable_KhachHang.getColumnModel().getColumn(4).setPreferredWidth(0);
            jTable_KhachHang.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        jButton_Them.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Them.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\math-add-icon.png")); // NOI18N
        jButton_Them.setText("Thêm");
        jButton_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemActionPerformed(evt);
            }
        });

        jButton_Xoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Xoa.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\delete-file-icon.png")); // NOI18N
        jButton_Xoa.setText("Xóa");
        jButton_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XoaActionPerformed(evt);
            }
        });

        jButton_Sua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Sua.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\edit-icon.png")); // NOI18N
        jButton_Sua.setText("Sửa");
        jButton_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SuaActionPerformed(evt);
            }
        });

        jButton_Luu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Luu.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\Save-icon.png")); // NOI18N
        jButton_Luu.setText("Lưu");
        jButton_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LuuActionPerformed(evt);
            }
        });

        jButton_Exit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Exit.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\Button-Close-icon.png")); // NOI18N
        jButton_Exit.setText("Thoát");
        jButton_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExitActionPerformed(evt);
            }
        });

        jButton_TimKiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_TimKiem.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\Zoom-icon.png")); // NOI18N
        jButton_TimKiem.setText("Tìm Kiếm");
        jButton_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TimKiemActionPerformed(evt);
            }
        });

        jButton_LamMoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_LamMoi.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\Reload-icon.png")); // NOI18N
        jButton_LamMoi.setText("Làm Mới");
        jButton_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_MaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_TenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(61, 61, 61)
                                .addComponent(jTextField_DiaChiKH, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_SDTKH, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(11, 11, 11))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jButton_Them)
                .addGap(6, 6, 6)
                .addComponent(jButton_Xoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Sua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_TimKiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_LamMoi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Luu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Exit))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jTextField_MaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(jTextField_DiaChiKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_TenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_SDTKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Xoa)
                    .addComponent(jButton_Them)
                    .addComponent(jButton_Sua)
                    .addComponent(jButton_TimKiem)
                    .addComponent(jButton_Luu)
                    .addComponent(jButton_Exit)
                    .addComponent(jButton_LamMoi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = -2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton_ExitActionPerformed

    private void jButton_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LuuActionPerformed
        // Xoa du lieu bi xoa
        for (int i = 0; i < maXoa.size(); i++) {
            KhachHang.xoaDuLieuKhach(maXoa.get(i));
        }
        
        // Them du lieu tu list vao bang:
        for (int i = 0; i < list.size(); i++) {
            if(i < listSize) {
                list.get(i).suaDuLieuKhach();
            } else {
                list.get(i).nhapDuLieuKhach();
            }
        }
        jButton_Luu.setEnabled(false);
        JOptionPane.showMessageDialog(null, "Lưu dữ liệu thành công!", "Thực hiện thành công", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton_LuuActionPerformed

    private void jButton_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SuaActionPerformed
        // TODO add your handling code here:
        if(jTable_KhachHang.getSelectedRowCount() == 1) {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            String maKH = jTextField_MaKH.getText();
            String tenKH = jTextField_TenKH.getText();
            String diaChi = jTextField_DiaChiKH.getText();
            String dienThoai = jTextField_SDTKH.getText();
            for (int i = 0; i < list.size(); i++) {
                if(list.get(i).getMaKH().equals(maKH)) {
                    list.get(i).setTenKH(tenKH);
                    list.get(i).setDiaChi(diaChi);
                    list.get(i).setDienThoai(dienThoai);
                }
            }
            showKhach(list);
            jButton_Luu.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Đã sửa khách hàng thành công!", "Thực hiện thành công", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if(jTable_KhachHang.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Bảng không có dữ liệu!", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Hay chọn từng cột để sửa!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton_SuaActionPerformed

    private void jButton_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XoaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable_KhachHang.getModel();
        if(jTable_KhachHang.getSelectedRowCount() == 1) {
            int selectedRow = jTable_KhachHang.getSelectedRow();
            String maKH = dtm.getValueAt(selectedRow, 1).toString();
            if(selectedRow < listSize) listSize--;
            maXoa.add(maKH);
            for (int i = 0; i < list.size(); i++) {
                if(list.get(i).getMaKH().equals(maKH)) {
                    list.remove(i);
                    break;
                }
            }
            showKhach(list);
            jButton_Luu.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Đã xóa khách hàng thành công!", "Thực hiện thành công", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if(jTable_KhachHang.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Bảng không có dữ liệu!", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Hay chọn từng cột để xóa!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        jTextField_MaKH.setText("");
        jTextField_TenKH.setText("");
        jTextField_DiaChiKH.setText("");
        jTextField_SDTKH.setText("");
    }//GEN-LAST:event_jButton_XoaActionPerformed

    private void jButton_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemActionPerformed
        // TODO add your handling code here:
        Khach_ThemView themKH = new Khach_ThemView(list);
        themKH.setLocationRelativeTo(null);
        themKH.setVisible(true);
    }//GEN-LAST:event_jButton_ThemActionPerformed

    private void jTable_KhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_KhachHangMouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable_KhachHang.getSelectedRow();
        DefaultTableModel dtm = (DefaultTableModel) jTable_KhachHang.getModel();
        jTextField_MaKH.setText(dtm.getValueAt(selectedRow, 1).toString());
        jTextField_TenKH.setText(dtm.getValueAt(selectedRow, 2).toString());
        jTextField_DiaChiKH.setText(dtm.getValueAt(selectedRow, 3).toString());
        jTextField_SDTKH.setText(dtm.getValueAt(selectedRow, 4).toString());
    }//GEN-LAST:event_jTable_KhachHangMouseClicked

    private void jTable_KhachHangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable_KhachHangKeyReleased
        // TODO add your handling code here:
        int selectedRow = jTable_KhachHang.getSelectedRow();
        DefaultTableModel dtm = (DefaultTableModel) jTable_KhachHang.getModel();
        jTextField_MaKH.setText(dtm.getValueAt(selectedRow, 1).toString());
        jTextField_TenKH.setText(dtm.getValueAt(selectedRow, 2).toString());
        jTextField_DiaChiKH.setText(dtm.getValueAt(selectedRow, 3).toString());
        jTextField_SDTKH.setText(dtm.getValueAt(selectedRow, 4).toString());
    }//GEN-LAST:event_jTable_KhachHangKeyReleased

    private void jButton_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TimKiemActionPerformed
        // TODO add your handling code here:
        //Xoa table
        DefaultTableModel dtm = (DefaultTableModel) jTable_KhachHang.getModel();
        while (dtm.getRowCount() > 0) {            
            dtm.removeRow(0);
        }
        
        String tenKH = jTextField_TenKH.getText();
        String diaChi = jTextField_DiaChiKH.getText();
        String sdt = jTextField_SDTKH.getText();
        
        if(tenKH.equals("") && diaChi.equals("") && sdt.equals("")) {
            JOptionPane.showMessageDialog(null, "Hãy nhập một điều kiện tìm kiếm!!!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else {
            List<KhachHang> listKH = new ArrayList<>();
            try {
                String connectionUrl = "jdbc:sqlserver://localhost:1433;DatabaseName=DBComputerStore;user=sa;password=123456;encrypt=true;trustServerCertificate=true";
                Connection con = DriverManager.getConnection(connectionUrl);
                String sql = "SELECT * FROM tblKhach WHERE 1 = 1";
                if(!tenKH.equals("")) {
                    sql = sql + " AND TenKH LIKE N'%" + tenKH +"%'";
                }
                if(!diaChi.equals("")) {
                    sql = sql + " AND DiaChi LIKE N'%" + diaChi +"%'";
                }
                if(!sdt.equals("")) {
                    sql = sql + " AND DienThoai LIKE '%" + sdt +"%'";
                }
                PreparedStatement pst = con.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();
                KhachHang kh;
                while(rs.next()) {
                    kh = new KhachHang(rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4));
                    listKH.add(kh);
                } 
                pst.close();
                con.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            
            if(listKH.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Không có khách hàng thỏa mãn điều kiện!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            } else {
                Object[] os = new Object[5];
                for (int i = 0; i < listKH.size(); i++) {
                    KhachHang get = listKH.get(i);
                    os[0] = i+1;
                    os[1] = get.getMaKH();
                    os[2] = get.getTenKH();
                    os[3] = get.getDiaChi();
                    os[4] = get.getDienThoai();
                    dtm.addRow(os);
                }
            }
        }
    }//GEN-LAST:event_jButton_TimKiemActionPerformed

    private void jButton_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LamMoiActionPerformed
        // TODO add your handling code here:
        showKhach(list);
        
        //Xoa text
        jTextField_MaKH.setText("");
        jTextField_TenKH.setText("");
        jTextField_DiaChiKH.setText("");
        jTextField_SDTKH.setText("");
    }//GEN-LAST:event_jButton_LamMoiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Exit;
    private javax.swing.JButton jButton_LamMoi;
    static javax.swing.JButton jButton_Luu;
    private javax.swing.JButton jButton_Sua;
    private javax.swing.JButton jButton_Them;
    private javax.swing.JButton jButton_TimKiem;
    private javax.swing.JButton jButton_Xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private static javax.swing.JTable jTable_KhachHang;
    private javax.swing.JTextField jTextField_DiaChiKH;
    private javax.swing.JTextField jTextField_MaKH;
    private javax.swing.JTextField jTextField_SDTKH;
    private javax.swing.JTextField jTextField_TenKH;
    // End of variables declaration//GEN-END:variables
}
