/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codeptit.QuanLyCuaHangLapTop.View;

import codeptit.QuanLyCuaHangLapTop.Model.TaiKhoan;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class LoginSysView extends javax.swing.JFrame {
    private TaiKhoan taiKhoan;
    /**
     * Creates new form LoginSysView
     */
    public LoginSysView() {
        initComponents();
        taiKhoan = new TaiKhoan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel_Login = new javax.swing.JLabel();
        jSeparator_Tren = new javax.swing.JSeparator();
        jPasswordField_MK = new javax.swing.JPasswordField();
        jLabel_MK = new javax.swing.JLabel();
        jLable_TK = new javax.swing.JLabel();
        jTextField_TK = new javax.swing.JTextField();
        jButton_Exit = new javax.swing.JButton();
        jSeparator_Duoi = new javax.swing.JSeparator();
        jButton_DangNhap = new javax.swing.JButton();
        jLabel_Login1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hệ Thống Đăng Nhập");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setName("LoginSys"); // NOI18N
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel_Login.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_Login.setForeground(new java.awt.Color(0, 0, 204));
        jLabel_Login.setText("Hệ Thống Quản Lý");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 97, 0, 0);
        getContentPane().add(jLabel_Login, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.ipadx = 350;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 24, 0, 24);
        getContentPane().add(jSeparator_Tren, gridBagConstraints);

        jPasswordField_MK.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField_MK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_MKActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 174;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 18, 0, 0);
        getContentPane().add(jPasswordField_MK, gridBagConstraints);

        jLabel_MK.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_MK.setText("Mật Khẩu:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 61, 0, 0);
        getContentPane().add(jLabel_MK, gridBagConstraints);

        jLable_TK.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLable_TK.setText("Tài Khoản:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 61, 0, 0);
        getContentPane().add(jLable_TK, gridBagConstraints);

        jTextField_TK.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_TK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_TKActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 174;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 18, 0, 0);
        getContentPane().add(jTextField_TK, gridBagConstraints);

        jButton_Exit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_Exit.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\Button-Close-icon.png")); // NOI18N
        jButton_Exit.setText("Thoát");
        jButton_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 55, 17, 0);
        getContentPane().add(jButton_Exit, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.ipadx = 350;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 24, 0, 24);
        getContentPane().add(jSeparator_Duoi, gridBagConstraints);

        jButton_DangNhap.setBackground(new java.awt.Color(0, 0, 255));
        jButton_DangNhap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_DangNhap.setForeground(new java.awt.Color(255, 255, 255));
        jButton_DangNhap.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\Login-icon.png")); // NOI18N
        jButton_DangNhap.setText("Đăng Nhập");
        jButton_DangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DangNhapActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 74, 17, 0);
        getContentPane().add(jButton_DangNhap, gridBagConstraints);

        jLabel_Login1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_Login1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_Login1.setText("Cửa Hàng Bán Máy Tính");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 68, 0, 0);
        getContentPane().add(jLabel_Login1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton_ExitActionPerformed

    private void jPasswordField_MKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_MKActionPerformed
        // TODO add your handling code here:
        jButton_DangNhapActionPerformed(evt);
    }//GEN-LAST:event_jPasswordField_MKActionPerformed

    private void jTextField_TKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_TKActionPerformed
        // TODO add your handling code here:
        jPasswordField_MK.requestFocus();
    }//GEN-LAST:event_jTextField_TKActionPerformed

    private void jButton_DangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DangNhapActionPerformed
        // TODO add your handling code here:
        String tk = jTextField_TK.getText();
        String mk = jPasswordField_MK.getText();
        taiKhoan.setTenTK(tk);
        taiKhoan.setMatKhau(mk);
        if(taiKhoan.kiemTraDangNhap()) {
            TaiKhoan temp = TaiKhoan.layTaiKhoan(tk);
            if(temp.getMaTK().contains("ADMIN")) {
                dispose();
                MainAdminView mainAdminView = new MainAdminView(tk);
                mainAdminView.setLocationRelativeTo(null);
                mainAdminView.setVisible(true);
            } else {
                dispose();
                MainUserView mainUserView = new MainUserView(tk);
                mainUserView.setLocationRelativeTo(null);
                mainUserView.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Tài khoản hoặc mật khẩu không hợp lệ!", "Login Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_DangNhapActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_DangNhap;
    private javax.swing.JButton jButton_Exit;
    private javax.swing.JLabel jLabel_Login;
    private javax.swing.JLabel jLabel_Login1;
    private javax.swing.JLabel jLabel_MK;
    private javax.swing.JLabel jLable_TK;
    private javax.swing.JPasswordField jPasswordField_MK;
    private javax.swing.JSeparator jSeparator_Duoi;
    private javax.swing.JSeparator jSeparator_Tren;
    private javax.swing.JTextField jTextField_TK;
    // End of variables declaration//GEN-END:variables

}
