/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codeptit.QuanLyCuaHangLapTop.View;

import codeptit.QuanLyCuaHangLapTop.Model.NhaCungCap;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class NhaCC_DanhMucView extends javax.swing.JFrame {
    private ArrayList<NhaCungCap> list;
    private int listSize;
    private List<String> maXoa;
    static int soMNCC;
    /**
     * Creates new form DanhMucKHView
     */
    public NhaCC_DanhMucView() {
        this.list = NhaCungCap.NCCList();
        maXoa = new ArrayList<>();
        listSize = list.size();
        if(list.isEmpty()) {
            soMNCC = 0;
        } else {
            soMNCC = Integer.valueOf(list.get(list.size()-1).getMaNCC().substring(3,6));
        }
        initComponents();
        showNCC(list);
        jTextField_MaNCC.setEditable(false);
        jButton_Luu.setEnabled(false);
    }
    
    public static void showNCC(ArrayList<NhaCungCap> list) {
        DefaultTableModel dtm = (DefaultTableModel) jTable_NCC.getModel();
        while (dtm.getRowCount() > 0) {            
            dtm.removeRow(dtm.getRowCount()-1);
        }
        Object[] os = new Object[3];
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        for (int i = 0; i < list.size(); i++) {
            os[0] = i+1;
            os[1] = list.get(i).getMaNCC();
            os[2] = list.get(i).getTenNCC();
            dtm.addRow(os);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_TenNCC = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_NCC = new javax.swing.JTable();
        jButton_Them = new javax.swing.JButton();
        jButton_Xoa = new javax.swing.JButton();
        jButton_Sua = new javax.swing.JButton();
        jButton_Luu = new javax.swing.JButton();
        jButton_Exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField_MaNCC = new javax.swing.JTextField();
        jButton_TimKiem = new javax.swing.JButton();
        jButton_LamMoi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Danh Mục Khách Hàng");
        setBackground(new java.awt.Color(255, 0, 0));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 153));
        jLabel6.setText("Mã nhà cung cấp:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("Tên nhà cung cấp:");

        jTextField_TenNCC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTable_NCC = new JTable() {
            public boolean isCellEditable(int row, int column) {
                for(int i = 0; i < jTable_NCC.getRowCount(); i++) {
                    if(row == i) return false;
                }
                return true;
            }
        };
        jTable_NCC.setBackground(new java.awt.Color(255, 153, 255));
        jTable_NCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã nhà cung cấp", "Tên nhà cung cấp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_NCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_NCCMouseClicked(evt);
            }
        });
        jTable_NCC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable_NCCKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_NCC);
        if (jTable_NCC.getColumnModel().getColumnCount() > 0) {
            jTable_NCC.getColumnModel().getColumn(0).setMinWidth(35);
            jTable_NCC.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTable_NCC.getColumnModel().getColumn(0).setMaxWidth(50);
            jTable_NCC.getColumnModel().getColumn(1).setMinWidth(110);
            jTable_NCC.getColumnModel().getColumn(1).setPreferredWidth(0);
            jTable_NCC.getColumnModel().getColumn(1).setMaxWidth(140);
        }

        jButton_Them.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton_Them.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\math-add-icon.png")); // NOI18N
        jButton_Them.setText("Thêm");
        jButton_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemActionPerformed(evt);
            }
        });

        jButton_Xoa.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton_Xoa.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\delete-file-icon.png")); // NOI18N
        jButton_Xoa.setText("Xóa");
        jButton_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XoaActionPerformed(evt);
            }
        });

        jButton_Sua.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton_Sua.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\edit-icon.png")); // NOI18N
        jButton_Sua.setText("Sửa");
        jButton_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SuaActionPerformed(evt);
            }
        });

        jButton_Luu.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton_Luu.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\Save-icon.png")); // NOI18N
        jButton_Luu.setText("Lưu");
        jButton_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LuuActionPerformed(evt);
            }
        });

        jButton_Exit.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton_Exit.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\Button-Close-icon.png")); // NOI18N
        jButton_Exit.setText("Thoát");
        jButton_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Danh Mục Nhà Cung Cấp");

        jTextField_MaNCC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton_TimKiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_TimKiem.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\Zoom-icon.png")); // NOI18N
        jButton_TimKiem.setText("Tìm Kiếm");
        jButton_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TimKiemActionPerformed(evt);
            }
        });

        jButton_LamMoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_LamMoi.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\Reload-icon.png")); // NOI18N
        jButton_LamMoi.setText("Làm Mới");
        jButton_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_MaNCC, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                    .addComponent(jTextField_TenNCC))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton_TimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_LamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton_Them)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton_Xoa)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton_Sua)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton_Luu)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton_Exit)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_MaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_TimKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_TenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_LamMoi))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Xoa)
                    .addComponent(jButton_Them)
                    .addComponent(jButton_Sua)
                    .addComponent(jButton_Luu)
                    .addComponent(jButton_Exit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemActionPerformed
        // TODO add your handling code here:
        NhaCC_Them themNCC = new NhaCC_Them(list);
        themNCC.setLocationRelativeTo(null);
        themNCC.setVisible(true);
    }//GEN-LAST:event_jButton_ThemActionPerformed

    private void jButton_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LuuActionPerformed
        // Xoa du lieu bi xoa
        for (int i = 0; i < maXoa.size(); i++) {
            NhaCungCap.xoaDuLieuNCC(maXoa.get(i));
        }
        
        // Them du lieu tu list vao bang:
        for (int i = 0; i < list.size(); i++) {
            if(i < listSize) {
                list.get(i).suaDuLieuNCC();
            } else {
                list.get(i).nhapDuLieuNCC();
            }
        }
        jButton_Luu.setEnabled(false);
        JOptionPane.showMessageDialog(null, "Lưu dữ liệu thành công!", "Thực hiện thành công", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton_LuuActionPerformed

    private void jButton_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton_ExitActionPerformed

    private void jTable_NCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_NCCMouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable_NCC.getSelectedRow();
        DefaultTableModel dtm = (DefaultTableModel) jTable_NCC.getModel();
        jTextField_MaNCC.setText(dtm.getValueAt(selectedRow, 1).toString());
        jTextField_TenNCC.setText(dtm.getValueAt(selectedRow, 2).toString());
    }//GEN-LAST:event_jTable_NCCMouseClicked

    private void jButton_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XoaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable_NCC.getModel();
        if(jTable_NCC.getSelectedRowCount() == 1) {
            int selectedRow = jTable_NCC.getSelectedRow();
            String maNCC = dtm.getValueAt(selectedRow, 1).toString();
            if(selectedRow < listSize) listSize--;
            maXoa.add(maNCC);
            for (int i = 0; i < list.size(); i++) {
                if(list.get(i).getMaNCC().equals(maNCC)) {
                    list.remove(i);
                    break;
                }
            }
            showNCC(list);
            JOptionPane.showMessageDialog(null, "Đã xóa nhà cung cấp thành công!", "Thực hiện thành công", JOptionPane.INFORMATION_MESSAGE);
            jButton_Luu.setEnabled(true);
        } else {
            if(jTable_NCC.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Bảng không có dữ liệu!", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Hay chọn từng cột để xóa!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        jTextField_MaNCC.setText("");
        jTextField_TenNCC.setText("");
    }//GEN-LAST:event_jButton_XoaActionPerformed

    private void jButton_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SuaActionPerformed
        // TODO add your handling code here:
        if(jTable_NCC.getSelectedRowCount() == 1) {
            String maNCC = jTextField_MaNCC.getText();
            String tenNCC = jTextField_TenNCC.getText();
            for (int i = 0; i < list.size(); i++) {
                if(list.get(i).getMaNCC().equals(maNCC)) {
                    list.get(i).setTenNCC(tenNCC);
                }
            }
            showNCC(list);
            JOptionPane.showMessageDialog(null, "Đã sửa nhà cung cấp thành công!", "Thực hiện thành công", JOptionPane.INFORMATION_MESSAGE);
            jButton_Luu.setEnabled(true);
        } else {
            if(jTable_NCC.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Bảng không có dữ liệu!", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Hay chọn từng cột để sửa!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton_SuaActionPerformed

    private void jTable_NCCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable_NCCKeyReleased
        // TODO add your handling code here:
        int selectedRow = jTable_NCC.getSelectedRow();
        DefaultTableModel dtm = (DefaultTableModel) jTable_NCC.getModel();
        jTextField_MaNCC.setText(dtm.getValueAt(selectedRow, 1).toString());
        jTextField_TenNCC.setText(dtm.getValueAt(selectedRow, 2).toString());
    }//GEN-LAST:event_jTable_NCCKeyReleased

    private void jButton_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LamMoiActionPerformed
        // TODO add your handling code here:
        showNCC(list);
        
        jTextField_MaNCC.setText("");
        jTextField_TenNCC.setText("");
    }//GEN-LAST:event_jButton_LamMoiActionPerformed

    private void jButton_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TimKiemActionPerformed
        // TODO add your handling code here:
        //Xoa bang
        DefaultTableModel dtm = (DefaultTableModel) jTable_NCC.getModel();
        while(jTable_NCC.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        
        String tenNCC = jTextField_TenNCC.getText();
        
        if(tenNCC.equals("")) {
            JOptionPane.showMessageDialog(null, "Hãy nhập một điều kiện tìm kiếm!!!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else {
            List<NhaCungCap> listNCC = new ArrayList<>();
            try {
                String connectionUrl = "jdbc:sqlserver://localhost:1433;DatabaseName=DBComputerStore;user=sa;password=123456;encrypt=true;trustServerCertificate=true";
                Connection con = DriverManager.getConnection(connectionUrl);
                String sql = "SELECT * FROM tblNhaCC WHERE TenNCC LIKE N'%" + tenNCC + "%'";
                PreparedStatement pst = con.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();
                NhaCungCap ncc;
                while(rs.next()) {
                    ncc = new NhaCungCap(rs.getString(1), rs.getString(2));
                    listNCC.add(ncc);
                } 
                pst.close();
                con.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            
            if(listNCC.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Không có nhà cung cấp thỏa mãn điều kiện!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            } else {
                Object[] os = new Object[3];
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                for (int i = 0; i < listNCC.size(); i++) {
                    NhaCungCap get = listNCC.get(i);
                    os[0] = i+1;
                    os[1] = get.getMaNCC();
                    os[2] = get.getTenNCC();
                    dtm.addRow(os);
                }
            }
        }
    }//GEN-LAST:event_jButton_TimKiemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Exit;
    private javax.swing.JButton jButton_LamMoi;
    static javax.swing.JButton jButton_Luu;
    private javax.swing.JButton jButton_Sua;
    private javax.swing.JButton jButton_Them;
    private javax.swing.JButton jButton_TimKiem;
    private javax.swing.JButton jButton_Xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private static javax.swing.JTable jTable_NCC;
    private javax.swing.JTextField jTextField_MaNCC;
    private javax.swing.JTextField jTextField_TenNCC;
    // End of variables declaration//GEN-END:variables
}
