/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codeptit.QuanLyCuaHangLapTop.View;

import codeptit.QuanLyCuaHangLapTop.Model.NhanVien;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class NhanVien_DanhMucView extends javax.swing.JFrame {

    private ArrayList<NhanVien> list;
    private int listSize;
    private List<String> maXoa;
    static int soMNV;

    /**
     * Creates new form NhanVien_DanhMucView
     */
    public NhanVien_DanhMucView() {
        this.list = NhanVien.nhanVienList();
        maXoa = new ArrayList<>();
        listSize = list.size();
        if(list.isEmpty()) {
            soMNV = 0;
        } else {
            soMNV = Integer.valueOf(list.get(list.size() - 1).getMaNV().substring(2, 5));
        }
        initComponents();
        showNhanVien(list);
        jTextField_MaNV.setEditable(false);
        jButton_Luu.setEnabled(false);
    }

    public static void showNhanVien(List<NhanVien> list) {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        DefaultTableModel dtm = (DefaultTableModel) jTable_NhanVien.getModel();
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        Object[] os = new Object[8];
        for (int i = 1; i < list.size(); i++) {
            os[0] = i;
            os[1] = list.get(i).getMaNV();
            os[2] = list.get(i).getTenNV();
            os[3] = list.get(i).getGioiTinh();
            os[4] = sdf.format(list.get(i).getNgaySinh());
            os[5] = list.get(i).getDiaChi();
            os[6] = list.get(i).getDienThoai();
            os[7] = list.get(i).getLuong();
            dtm.addRow(os);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup_Sex = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jTextField_MaNV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_TenNV = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_NgaySinh = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_Luong = new javax.swing.JTextField();
        jTextField_SDT = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_DiaChi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_NhanVien = new javax.swing.JTable();
        jButton_Them = new javax.swing.JButton();
        jButton_Xoa = new javax.swing.JButton();
        jButton_Sua = new javax.swing.JButton();
        jButton_TimKiem = new javax.swing.JButton();
        jButton_LamMoi = new javax.swing.JButton();
        jButton_Luu = new javax.swing.JButton();
        jButton_Exit = new javax.swing.JButton();
        jRadioButton_Nam = new javax.swing.JRadioButton();
        jRadioButton_Nu = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Danh Mục Nhân Viên");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 13, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 64, 425, 10));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 153));
        jLabel6.setText("Mã nhân viên:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 84, -1, -1));

        jTextField_MaNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jTextField_MaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 81, 140, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("Tên nhân viên:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 125, -1, -1));

        jTextField_TenNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jTextField_TenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 122, 140, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 153));
        jLabel4.setText("Giới tính:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 166, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 153));
        jLabel5.setText("Ngày sinh:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 84, -1, -1));

        jTextField_NgaySinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jTextField_NgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 81, 140, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 153));
        jLabel9.setText("Lương:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 125, -1, -1));

        jTextField_Luong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jTextField_Luong, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 122, 140, -1));

        jTextField_SDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jTextField_SDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 81, 140, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 153));
        jLabel8.setText("Số điện thoại:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 81, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 153));
        jLabel7.setText("Địa chỉ:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 125, -1, -1));

        jTextField_DiaChi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jTextField_DiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 122, 140, -1));

        jTable_NhanVien = new JTable() {
            public boolean isCellEditable(int row, int column) {
                for(int i = 0; i < jTable_NhanVien.getRowCount(); i++) {
                    if(row == i) return false;
                }
                return true;
            }
        };
        jTable_NhanVien.setBackground(new java.awt.Color(255, 153, 153));
        jTable_NhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã nhân viên", "Tên nhân viên", "Giới Tính", "Ngày sinh", "Địa chỉ", "Số điện thoại", "Lương"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_NhanVienMouseClicked(evt);
            }
        });
        jTable_NhanVien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable_NhanVienKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_NhanVien);
        if (jTable_NhanVien.getColumnModel().getColumnCount() > 0) {
            jTable_NhanVien.getColumnModel().getColumn(0).setMinWidth(35);
            jTable_NhanVien.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTable_NhanVien.getColumnModel().getColumn(0).setMaxWidth(60);
            jTable_NhanVien.getColumnModel().getColumn(1).setMinWidth(90);
            jTable_NhanVien.getColumnModel().getColumn(1).setPreferredWidth(0);
            jTable_NhanVien.getColumnModel().getColumn(1).setMaxWidth(120);
            jTable_NhanVien.getColumnModel().getColumn(2).setMinWidth(130);
            jTable_NhanVien.getColumnModel().getColumn(2).setPreferredWidth(0);
            jTable_NhanVien.getColumnModel().getColumn(2).setMaxWidth(170);
            jTable_NhanVien.getColumnModel().getColumn(3).setMinWidth(65);
            jTable_NhanVien.getColumnModel().getColumn(3).setPreferredWidth(0);
            jTable_NhanVien.getColumnModel().getColumn(3).setMaxWidth(80);
            jTable_NhanVien.getColumnModel().getColumn(4).setMinWidth(80);
            jTable_NhanVien.getColumnModel().getColumn(4).setPreferredWidth(0);
            jTable_NhanVien.getColumnModel().getColumn(4).setMaxWidth(100);
            jTable_NhanVien.getColumnModel().getColumn(6).setMinWidth(90);
            jTable_NhanVien.getColumnModel().getColumn(6).setPreferredWidth(0);
            jTable_NhanVien.getColumnModel().getColumn(6).setMaxWidth(120);
            jTable_NhanVien.getColumnModel().getColumn(7).setMinWidth(75);
            jTable_NhanVien.getColumnModel().getColumn(7).setPreferredWidth(0);
            jTable_NhanVien.getColumnModel().getColumn(7).setMaxWidth(90);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 206, 733, 212));

        jButton_Them.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Them.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\math-add-icon.png")); // NOI18N
        jButton_Them.setText("Thêm");
        jButton_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Them, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 431, -1, -1));

        jButton_Xoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Xoa.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\delete-file-icon.png")); // NOI18N
        jButton_Xoa.setText("Xóa");
        jButton_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XoaActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 431, -1, -1));

        jButton_Sua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Sua.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\edit-icon.png")); // NOI18N
        jButton_Sua.setText("Sửa");
        jButton_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SuaActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 431, -1, -1));

        jButton_TimKiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_TimKiem.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\Zoom-icon.png")); // NOI18N
        jButton_TimKiem.setText("Tìm Kiếm");
        jButton_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TimKiemActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_TimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 431, -1, -1));

        jButton_LamMoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_LamMoi.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\Reload-icon.png")); // NOI18N
        jButton_LamMoi.setText("Làm Mới");
        jButton_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LamMoiActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_LamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 431, -1, -1));

        jButton_Luu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Luu.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\Save-icon.png")); // NOI18N
        jButton_Luu.setText("Lưu");
        jButton_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LuuActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Luu, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 431, -1, -1));

        jButton_Exit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Exit.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\Button-Close-icon.png")); // NOI18N
        jButton_Exit.setText("Thoát");
        jButton_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExitActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 431, -1, -1));

        buttonGroup_Sex.add(jRadioButton_Nam);
        jRadioButton_Nam.setText("Nam");
        jPanel1.add(jRadioButton_Nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 163, -1, -1));

        buttonGroup_Sex.add(jRadioButton_Nu);
        jRadioButton_Nu.setText("Nữ");
        jPanel1.add(jRadioButton_Nu, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 163, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemActionPerformed
        // TODO add your handling code here:
        NhanVien_ThemView nvtv = new NhanVien_ThemView(list);
        nvtv.setLocationRelativeTo(null);
        nvtv.setVisible(true);
    }//GEN-LAST:event_jButton_ThemActionPerformed

    private void jButton_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XoaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable_NhanVien.getModel();
        if (jTable_NhanVien.getSelectedRowCount() == 1) {
            int selectedRow = jTable_NhanVien.getSelectedRow();
            if(selectedRow < listSize) listSize--;
            maXoa.add(dtm.getValueAt(selectedRow, 1).toString());
            list.remove(selectedRow);
            showNhanVien(list);
            jButton_Luu.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Đã xóa nhân viên thành công!", "Thực hiện thành công", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (jTable_NhanVien.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Bảng không có dữ liệu!", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Hay chọn từng cột để xóa!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        jTextField_MaNV.setText("");
        jTextField_TenNV.setText("");
        buttonGroup_Sex.clearSelection();
        jTextField_NgaySinh.setText("");
        jTextField_DiaChi.setText("");
        jTextField_SDT.setText("");
        jTextField_Luong.setText("");
    }//GEN-LAST:event_jButton_XoaActionPerformed

    private void jButton_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SuaActionPerformed
        // TODO add your handling code here:
        if (jTable_NhanVien.getSelectedRowCount() == 1) {
            int selectedRow = jTable_NhanVien.getSelectedRow();
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            String maNV = jTextField_MaNV.getText();
            String tenNV = jTextField_TenNV.getText();
            String gioiTinh = "";
            if (jRadioButton_Nam.isSelected()) {
                gioiTinh = "Nam";
            } else {
                gioiTinh = "Nữ";
            }
            String ngaySinh = jTextField_NgaySinh.getText();
            String diaChi = jTextField_DiaChi.getText();
            String sdt = jTextField_SDT.getText();
            String luong = jTextField_Luong.getText();
            for (int i = 0; i < list.size(); i++) {
                if (list.get(i).getMaNV().equals(maNV)) {
                    try {
                        list.get(i).setTenNV(tenNV);
                        list.get(i).setGioiTinh(gioiTinh);
                        list.get(i).setNgaySinh(sdf.parse(ngaySinh));
                        list.get(i).setDiaChi(diaChi);
                        list.get(i).setDienThoai(sdt);
                        list.get(i).setLuong(Long.valueOf(luong));
                    } catch (ParseException ex) {
                        Logger.getLogger(NhanVien_DanhMucView.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            showNhanVien(list);
            jButton_Luu.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Đã sửa nhân viên thành công!", "Thực hiện thành công", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (jTable_NhanVien.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Bảng không có dữ liệu!", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Hay chọn từng cột để sửa!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton_SuaActionPerformed

    private void jButton_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TimKiemActionPerformed
        // TODO add your handling code here:
        // Xoa table
        DefaultTableModel dtm = (DefaultTableModel) jTable_NhanVien.getModel();
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        
        String tenNV = jTextField_TenNV.getText();
        String gioiTinh = "";
        if (jRadioButton_Nam.isSelected()) {
            gioiTinh = "Nam";
        }
        if (jRadioButton_Nu.isSelected()) {
            gioiTinh = "Nữ";
        }
        String ngaySinh = "";
        if(!jTextField_NgaySinh.getText().toString().equals("")) {
            try {
                ngaySinh = format.format(sdf.parse(jTextField_NgaySinh.getText()));
            } catch (ParseException ex) {
                Logger.getLogger(NhanVien_DanhMucView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        String diaChi = jTextField_DiaChi.getText();
        String sdt = jTextField_SDT.getText();
        String luong = jTextField_Luong.getText();

        if (tenNV.equals("") && gioiTinh.equals("") && ngaySinh.equals("") && diaChi.equals("") && sdt.equals("") && luong.equals("")) {
            JOptionPane.showMessageDialog(null, "Hãy nhập một điều kiện tìm kiếm!!!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else {
            List<NhanVien> listNV = new ArrayList<>();
            try {
                String connectionUrl = "jdbc:sqlserver://localhost:1433;DatabaseName=DBComputerStore;user=sa;password=123456;encrypt=true;trustServerCertificate=true";
                Connection con = DriverManager.getConnection(connectionUrl);
                String sql = "SELECT * FROM tblNhanVien WHERE 1 = 1";
                if (!tenNV.equals("")) {
                    sql = sql + " AND TenNV LIKE N'%" + tenNV + "%'";
                }
                if (!gioiTinh.equals("")) {
                    sql = sql + " AND GioiTinh LIKE N'%" + gioiTinh + "%'";
                }
                if (!ngaySinh.equals("")) {
                    sql = sql + " AND NgaySinh = '" + ngaySinh + "'";
                }
                if (!diaChi.equals("")) {
                    sql = sql + " AND DiaChi LIKE N'%" + diaChi + "%'";
                }
                if (!sdt.equals("")) {
                    sql = sql + " AND DienThoai LIKE '%" + sdt + "%'";
                }
                if (!luong.equals("")) {
                    sql = sql + " AND Luong <= " + luong;
                }
                PreparedStatement pst = con.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();
                NhanVien nv;
                while (rs.next()) {
                    nv = new NhanVien(rs.getString(1), rs.getString(2), rs.getString(3), rs.getDate(4), rs.getString(5), rs.getString(6), rs.getLong(7));
                    listNV.add(nv);
                }
                pst.close();
                con.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }

            Object[] os = new Object[8];
            int dem = 1;
            for (int i = 0; i < listNV.size(); i++) {
                if (listNV.get(i).getMaNV().equals("Admin")) {
                    continue;
                }
                os[0] = dem++;
                os[1] = listNV.get(i).getMaNV();
                os[2] = listNV.get(i).getTenNV();
                os[3] = listNV.get(i).getGioiTinh();
                os[4] = sdf.format(listNV.get(i).getNgaySinh());
                os[5] = listNV.get(i).getDiaChi();
                os[6] = listNV.get(i).getDienThoai();
                os[7] = listNV.get(i).getLuong();
                dtm.addRow(os);
            }
            if (dem == 1) {
                JOptionPane.showMessageDialog(null, "Không có nhân viên thỏa mãn điều kiện!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton_TimKiemActionPerformed

    private void jButton_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LamMoiActionPerformed
        // TODO add your handling code here:
        showNhanVien(list);

        //Xoa text
        jTextField_MaNV.setText("");
        jTextField_TenNV.setText("");
        buttonGroup_Sex.clearSelection();
        jTextField_NgaySinh.setText("");
        jTextField_DiaChi.setText("");
        jTextField_SDT.setText("");
        jTextField_Luong.setText("");
    }//GEN-LAST:event_jButton_LamMoiActionPerformed

    private void jButton_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LuuActionPerformed
        // Xoa du lieu bi xoa
        for (int i = 0; i < maXoa.size(); i++) {
            NhanVien.xoaDuLieuNhanVien(maXoa.get(i));
        }
        
        // Them du lieu tu list vao bang:
        for (int i = 0; i < list.size(); i++) {
            if(i < listSize) {
                list.get(i).suaDuLieuNhanVien();
            } else {
                list.get(i).nhapDuLieuNhanVien();
            }
        }
        jButton_Luu.setEnabled(false);
        JOptionPane.showMessageDialog(null, "Lưu dữ liệu thành công!", "Thực hiện thành công", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton_LuuActionPerformed

    private void jButton_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton_ExitActionPerformed

    private void jTable_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_NhanVienMouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable_NhanVien.getSelectedRow();
        DefaultTableModel dtm = (DefaultTableModel) jTable_NhanVien.getModel();
        jTextField_MaNV.setText(dtm.getValueAt(selectedRow, 1).toString());
        jTextField_TenNV.setText(dtm.getValueAt(selectedRow, 2).toString());
        if (dtm.getValueAt(selectedRow, 3).toString().equals("Nam")) {
            jRadioButton_Nu.setSelected(false);
            jRadioButton_Nam.setSelected(true);
        } else {
            jRadioButton_Nam.setSelected(false);
            jRadioButton_Nu.setSelected(true);
        }
        jTextField_NgaySinh.setText(dtm.getValueAt(selectedRow, 4).toString());
        jTextField_DiaChi.setText(dtm.getValueAt(selectedRow, 5).toString());
        jTextField_SDT.setText(dtm.getValueAt(selectedRow, 6).toString());
        jTextField_Luong.setText(dtm.getValueAt(selectedRow, 7).toString());
    }//GEN-LAST:event_jTable_NhanVienMouseClicked

    private void jTable_NhanVienKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable_NhanVienKeyReleased
        // TODO add your handling code here:
        int selectedRow = jTable_NhanVien.getSelectedRow();
        DefaultTableModel dtm = (DefaultTableModel) jTable_NhanVien.getModel();
        jTextField_MaNV.setText(dtm.getValueAt(selectedRow, 1).toString());
        jTextField_TenNV.setText(dtm.getValueAt(selectedRow, 2).toString());
        if (dtm.getValueAt(selectedRow, 3).toString().equals("Nam")) {
            jRadioButton_Nu.setSelected(false);
            jRadioButton_Nam.setSelected(true);
        } else {
            jRadioButton_Nam.setSelected(false);
            jRadioButton_Nu.setSelected(true);
        }
        jTextField_NgaySinh.setText(dtm.getValueAt(selectedRow, 4).toString());
        jTextField_DiaChi.setText(dtm.getValueAt(selectedRow, 5).toString());
        jTextField_SDT.setText(dtm.getValueAt(selectedRow, 6).toString());
        jTextField_Luong.setText(dtm.getValueAt(selectedRow, 7).toString());
    }//GEN-LAST:event_jTable_NhanVienKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_Sex;
    private javax.swing.JButton jButton_Exit;
    private javax.swing.JButton jButton_LamMoi;
    static javax.swing.JButton jButton_Luu;
    private javax.swing.JButton jButton_Sua;
    private javax.swing.JButton jButton_Them;
    private javax.swing.JButton jButton_TimKiem;
    private javax.swing.JButton jButton_Xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton_Nam;
    private javax.swing.JRadioButton jRadioButton_Nu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private static javax.swing.JTable jTable_NhanVien;
    private javax.swing.JTextField jTextField_DiaChi;
    private javax.swing.JTextField jTextField_Luong;
    private javax.swing.JTextField jTextField_MaNV;
    private javax.swing.JTextField jTextField_NgaySinh;
    private javax.swing.JTextField jTextField_SDT;
    private javax.swing.JTextField jTextField_TenNV;
    // End of variables declaration//GEN-END:variables
}
