/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codeptit.QuanLyCuaHangLapTop.View;

import codeptit.QuanLyCuaHangLapTop.Model.TaiKhoan;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class TaiKhoan_DanhMucView extends javax.swing.JFrame {

    private ArrayList<TaiKhoan> list;
    private int listSize;
    private List<String> maXoa;
    static int soMTK;

    /**
     * Creates new form TaiKhoan_DanhMucView
     */
    public TaiKhoan_DanhMucView() {
        this.list = TaiKhoan.taiKhoanList();
        maXoa = new ArrayList<>();
        listSize = list.size();
        if (list.isEmpty()) {
            soMTK = 0;
        } else {
            soMTK = Integer.valueOf(list.get(list.size() - 1).getMaTK().substring(2, 5));
        }
        initComponents();
        showTaiKhoan(list);
        jTextField_MaTK.setEditable(false);
        jButton_Luu.setEnabled(false);
    }

    public static void showTaiKhoan(List<TaiKhoan> list) {
        DefaultTableModel dtm = (DefaultTableModel) jTable_TaiKhoan.getModel();
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        Object[] os = new Object[4];
        for (int i = 0; i < list.size(); i++) {
            os[0] = i + 1;
            os[1] = list.get(i).getMaTK();
            os[2] = list.get(i).getTenTK();
            os[3] = list.get(i).getMatKhau();
            dtm.addRow(os);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_MaTK = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_TenTK = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_TaiKhoan = new javax.swing.JTable();
        jButton_Them = new javax.swing.JButton();
        jButton_Xoa = new javax.swing.JButton();
        jButton_Sua = new javax.swing.JButton();
        jButton_LamMoi = new javax.swing.JButton();
        jButton_Luu = new javax.swing.JButton();
        jButton_TimKiem = new javax.swing.JButton();
        jButton_Exit = new javax.swing.JButton();
        jTextField_MatKhau = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Danh Mục Tài Khoản");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 204));
        jLabel2.setText("Mã tài khoản:");

        jTextField_MaTK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 204));
        jLabel3.setText("Tên tài khoản:");

        jTextField_TenTK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 204));
        jLabel4.setText("Mật khẩu:");

        jTable_TaiKhoan = new JTable() {
            public boolean isCellEditable(int row, int column) {
                for(int i = 0; i < jTable_TaiKhoan.getRowCount(); i++) {
                    if(row == i) return false;
                }
                return true;
            }
        };
        jTable_TaiKhoan.setBackground(new java.awt.Color(255, 153, 153));
        jTable_TaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã tài khoản", "Tên tài khoản", "Mật khẩu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_TaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_TaiKhoanMouseClicked(evt);
            }
        });
        jTable_TaiKhoan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable_TaiKhoanKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_TaiKhoan);
        if (jTable_TaiKhoan.getColumnModel().getColumnCount() > 0) {
            jTable_TaiKhoan.getColumnModel().getColumn(0).setMinWidth(40);
            jTable_TaiKhoan.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTable_TaiKhoan.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        jButton_Them.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Them.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\math-add-icon.png")); // NOI18N
        jButton_Them.setText("Thêm");
        jButton_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemActionPerformed(evt);
            }
        });

        jButton_Xoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Xoa.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\delete-file-icon.png")); // NOI18N
        jButton_Xoa.setText("Xóa");
        jButton_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XoaActionPerformed(evt);
            }
        });

        jButton_Sua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Sua.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\edit-icon.png")); // NOI18N
        jButton_Sua.setText("Sửa");
        jButton_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SuaActionPerformed(evt);
            }
        });

        jButton_LamMoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_LamMoi.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\Reload-icon.png")); // NOI18N
        jButton_LamMoi.setText("Làm Mới");
        jButton_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LamMoiActionPerformed(evt);
            }
        });

        jButton_Luu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Luu.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\Save-icon.png")); // NOI18N
        jButton_Luu.setText("Lưu");
        jButton_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LuuActionPerformed(evt);
            }
        });

        jButton_TimKiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_TimKiem.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\Zoom-icon.png")); // NOI18N
        jButton_TimKiem.setText("Tìm Kiếm");
        jButton_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TimKiemActionPerformed(evt);
            }
        });

        jButton_Exit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Exit.setIcon(new javax.swing.ImageIcon("D:\\Dai Hoc\\LapTrinhHuongDoiTuong\\QuanLyCuaHangMayTinh\\icon\\Button-Close-icon.png")); // NOI18N
        jButton_Exit.setText("Thoát");
        jButton_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExitActionPerformed(evt);
            }
        });

        jTextField_MatKhau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(47, 47, 47)))
                .addGap(109, 109, 109))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_Them)
                                .addGap(2, 2, 2)
                                .addComponent(jButton_Xoa)
                                .addGap(1, 1, 1)
                                .addComponent(jButton_Sua)
                                .addGap(2, 2, 2)
                                .addComponent(jButton_TimKiem)
                                .addGap(2, 2, 2)
                                .addComponent(jButton_LamMoi)
                                .addGap(2, 2, 2)
                                .addComponent(jButton_Luu)
                                .addGap(0, 0, 0)
                                .addComponent(jButton_Exit)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_MaTK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_TenTK, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_MatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_MaTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_TenTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_MatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Them)
                    .addComponent(jButton_Xoa)
                    .addComponent(jButton_Sua)
                    .addComponent(jButton_LamMoi)
                    .addComponent(jButton_Luu)
                    .addComponent(jButton_TimKiem)
                    .addComponent(jButton_Exit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemActionPerformed
        // TODO add your handling code here:
        TaiKhoan_ThemView tktv = new TaiKhoan_ThemView(list);
        tktv.setLocationRelativeTo(null);
        tktv.setVisible(true);
    }//GEN-LAST:event_jButton_ThemActionPerformed

    private void jButton_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XoaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable_TaiKhoan.getModel();
        if (jTable_TaiKhoan.getSelectedRowCount() == 1) {
            int selectedRow = jTable_TaiKhoan.getSelectedRow();
            if(selectedRow < listSize) listSize--;
            maXoa.add(dtm.getValueAt(selectedRow, 1).toString());
            list.remove(selectedRow);
            showTaiKhoan(list);
            jButton_Luu.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Đã xóa tài khoản thành công!", "Thực hiện thành công", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (jTable_TaiKhoan.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Bảng không có dữ liệu!", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Hay chọn từng cột để xóa!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        jTextField_MaTK.setText("");
        jTextField_TenTK.setText("");
        jTextField_MatKhau.setText("");
    }//GEN-LAST:event_jButton_XoaActionPerformed

    private void jButton_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SuaActionPerformed
        // TODO add your handling code here:
        if (jTable_TaiKhoan.getSelectedRowCount() == 1) {
            int selectedRow = jTable_TaiKhoan.getSelectedRow();
            String maTK = jTextField_MaTK.getText();
            String tenTK = jTextField_TenTK.getText();
            String matKhau = jTextField_MatKhau.getText();
            for (int i = 0; i < list.size(); i++) {
                if (list.get(i).getMaTK().equals(maTK)) {
                    list.get(i).setMaTK(maTK);
                    list.get(i).setTenTK(tenTK);
                    list.get(i).setMatKhau(matKhau);
                }
            }
            showTaiKhoan(list);
            jButton_Luu.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Đã sửa tài khoản thành công!", "Thực hiện thành công", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (jTable_TaiKhoan.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Bảng không có dữ liệu!", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Hay chọn từng cột để sửa!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton_SuaActionPerformed

    private void jButton_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TimKiemActionPerformed
        // TODO add your handling code here:
        // Xoa table
        DefaultTableModel dtm = (DefaultTableModel) jTable_TaiKhoan.getModel();
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }

        String tenTK = jTextField_TenTK.getText();
        String matKhau = jTextField_MatKhau.getText();

        if (tenTK.equals("") && matKhau.equals("")) {
            JOptionPane.showMessageDialog(null, "Hãy nhập một điều kiện tìm kiếm!!!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else {
            List<TaiKhoan> listTK = new ArrayList<>();
            try {
                String connectionUrl = "jdbc:sqlserver://localhost:1433;DatabaseName=DBComputerStore;user=sa;password=123456;encrypt=true;trustServerCertificate=true";
                Connection con = DriverManager.getConnection(connectionUrl);
                String sql = "SELECT * FROM tblLoginSys WHERE 1 = 1";
                if (!tenTK.equals("")) {
                    sql = sql + " AND TenTK LIKE '%" + tenTK + "%'";
                }
                if (!matKhau.equals("")) {
                    sql = sql + " AND MatKhau LIKE '%" + matKhau + "%'";
                }
                PreparedStatement pst = con.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();
                TaiKhoan tk;
                while (rs.next()) {
                    tk = new TaiKhoan(rs.getString(1), rs.getString(2), rs.getString(3));
                    listTK.add(tk);
                }
                pst.close();
                con.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }

            Object[] os = new Object[4];
            int dem = 1;
            for (int i = 0; i < listTK.size(); i++) {
                os[0] = dem++;
                os[1] = listTK.get(i).getMaTK();
                os[2] = listTK.get(i).getTenTK();
                os[3] = listTK.get(i).getMatKhau();
                dtm.addRow(os);
            }
            if (dem == 1) {
                JOptionPane.showMessageDialog(null, "Không có tài khoản thỏa mãn điều kiện!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton_TimKiemActionPerformed

    private void jButton_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LamMoiActionPerformed
        // TODO add your handling code here:
        showTaiKhoan(list);

        //Xoa text
        jTextField_MaTK.setText("");
        jTextField_TenTK.setText("");
        jTextField_MatKhau.setText("");
    }//GEN-LAST:event_jButton_LamMoiActionPerformed

    private void jButton_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LuuActionPerformed
        // Xoa du lieu bi xoa
        for (int i = 0; i < maXoa.size(); i++) {
            TaiKhoan.xoaDuLieuTaiKhoan(maXoa.get(i));
        }
        
        // Them du lieu tu list vao bang:
        for (int i = 0; i < list.size(); i++) {
            if(i < listSize) {
                list.get(i).suaDuLieuTaiKhoan();
            } else {
                list.get(i).nhapDuLieuTaiKhoan();
            }
        }
        jButton_Luu.setEnabled(false);
        JOptionPane.showMessageDialog(null, "Lưu dữ liệu thành công!", "Thực hiện thành công", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton_LuuActionPerformed

    private void jButton_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton_ExitActionPerformed

    private void jTable_TaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_TaiKhoanMouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable_TaiKhoan.getSelectedRow();
        DefaultTableModel dtm = (DefaultTableModel) jTable_TaiKhoan.getModel();
        jTextField_MaTK.setText(dtm.getValueAt(selectedRow, 1).toString());
        jTextField_TenTK.setText(dtm.getValueAt(selectedRow, 2).toString());
        jTextField_MatKhau.setText(dtm.getValueAt(selectedRow, 3).toString());
    }//GEN-LAST:event_jTable_TaiKhoanMouseClicked

    private void jTable_TaiKhoanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable_TaiKhoanKeyReleased
        // TODO add your handling code here:
        int selectedRow = jTable_TaiKhoan.getSelectedRow();
        DefaultTableModel dtm = (DefaultTableModel) jTable_TaiKhoan.getModel();
        jTextField_MaTK.setText(dtm.getValueAt(selectedRow, 1).toString());
        jTextField_TenTK.setText(dtm.getValueAt(selectedRow, 2).toString());
        jTextField_MatKhau.setText(dtm.getValueAt(selectedRow, 3).toString());
    }//GEN-LAST:event_jTable_TaiKhoanKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Exit;
    private javax.swing.JButton jButton_LamMoi;
    static javax.swing.JButton jButton_Luu;
    private javax.swing.JButton jButton_Sua;
    private javax.swing.JButton jButton_Them;
    private javax.swing.JButton jButton_TimKiem;
    private javax.swing.JButton jButton_Xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private static javax.swing.JTable jTable_TaiKhoan;
    private javax.swing.JTextField jTextField_MaTK;
    private javax.swing.JTextField jTextField_MatKhau;
    private javax.swing.JTextField jTextField_TenTK;
    // End of variables declaration//GEN-END:variables
}
